import * as THREE from 'three';
import {createWonderlandStory} from './scenes.js';
import {createWonderlandObjects} from './wonderland.js';
export function createARLayer(container,onContextLost,interaction,onProgress=()=>{}){
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power',preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));renderer.setClearColor(0,0);container.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,20);camera.rotation.order='YXZ';scene.add(new THREE.HemisphereLight(0xffffff,0x5e7a84,2.5));const light=new THREE.DirectionalLight(0xffe4b8,3);light.position.set(-2,4,5);scene.add(light);
 const anchor=new THREE.Group();scene.add(anchor);const wonderland=createWonderlandObjects();anchor.add(wonderland.root);const story=createWonderlandStory();let wonderlandPose=story.snapshot(),active=false,previous=0,lastMessage='',elapsed=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
 function resize(){const{width,height}=container.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(container);resize();const lost=e=>{e.preventDefault();onContextLost();};renderer.domElement.addEventListener('webglcontextlost',lost);
 function placeWonderland(){anchor.position.set(0,0,0);anchor.rotation.set(0,0,0);}
 renderer.setAnimationLoop(now=>{const delta=previous?Math.min((now-previous)/1000,.05):0;previous=now;if(document.hidden)return;if(active){elapsed+=delta;const view=interaction.update();camera.position.set(0,0,0);camera.rotation.set(view.pitch,view.yaw,0,'YXZ');camera.updateMatrixWorld();placeWonderland();wonderlandPose=story.update(delta);wonderland.update(wonderlandPose.state,wonderlandPose.age,elapsed,reduced.matches);const key=`${wonderlandPose.state}|${wonderlandPose.message}|${elapsed<3.5}`;if(key!==lastMessage){lastMessage=key;onProgress({state:wonderlandPose.state,message:wonderlandPose.message,safety:elapsed<3.5});}}else{camera.position.set(0,0,0);camera.rotation.set(0,0,0);placeWonderland();wonderland.root.visible=false;}renderer.render(scene,camera);});
 return{start(){active=true;elapsed=0;lastMessage='';story.reset();wonderland.reset();wonderland.root.visible=true;},stop(){active=false;wonderland.root.visible=false;},get phaseState(){return story.state;},dispose(){renderer.setAnimationLoop(null);observer.disconnect();renderer.domElement.removeEventListener('webglcontextlost',lost);const gs=new Set(),ms=new Set();scene.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)ms.add(o.material);});gs.forEach(g=>g.dispose());ms.forEach(m=>{m.map?.dispose();m.dispose();});renderer.dispose();renderer.domElement.remove();}};
}
export function cameraErrorMessage(error){switch(error.name){case'NotAllowedError':return'カメラを許可してください。拒否した場合はブラウザのサイト設定から変更できます。';case'NotFoundError':return'カメラが見つかりません。カメラ付きのスマートフォンで開いてください。';case'NotReadableError':return'カメラを使用できません。他のアプリでカメラを閉じて、もう一度お試しください。';default:return'カメラを起動できませんでした。SafariまたはChromeで開き直してください。';}}
