import * as THREE from 'three';
import {createSceneManager,SceneType} from './scene-manager.js';
import {createWorld01} from './scenes/world01.js';
import {createWorld02} from './scenes/world02.js';
import {createWorld03} from './scenes/world03.js';
import {createWorld04} from './scenes/world04.js';
import {getTimeTheme} from './time-theme.js';
export function createARLayer(container,onContextLost,interaction){const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power',preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,1,.1,30);camera.rotation.order='YXZ';const hemisphere=new THREE.HemisphereLight(0xefe4ce,0x29231f,1.15),key=new THREE.DirectionalLight(0xffefd3,1.1);key.position.set(-2,4,3);key.castShadow=true;scene.add(hemisphere,key);const applyLighting=event=>{const t=event.detail;hemisphere.color.setHex(t.sky);hemisphere.groundColor.setHex(t.ground);key.color.setHex(t.key);key.intensity=t.keyIntensity*.88;};applyLighting({detail:getTimeTheme()});document.documentElement.addEventListener('wonderlandthemechange',applyLighting);const worlds={world01:createWorld01(),world02:createWorld02(),world03:createWorld03(),world04:createWorld04()};Object.values(worlds).forEach(world=>{world.root.visible=false;scene.add(world.root);});const manager=createSceneManager(worlds);let active=false,paused=false,previous=0,elapsed=0;function resize(){const{width,height}=container.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix();manager.responsive(width,height);}const observer=new ResizeObserver(resize);observer.observe(container);resize();const lost=e=>{e.preventDefault();onContextLost();};renderer.domElement.addEventListener('webglcontextlost',lost);renderer.setAnimationLoop(now=>{const delta=previous?Math.min((now-previous)/1000,.05):0;previous=now;if(!active||document.hidden)return;if(!paused)elapsed+=delta;const view=interaction.update();camera.position.set(0,0,0);camera.rotation.set(view.pitch,view.yaw,0,'YXZ');if(!paused)manager.update(elapsed,delta,{view,camera});renderer.render(scene,camera);});return{start(){active=true;paused=false;elapsed=0;manager.reset();},stop(){active=false;paused=false;Object.values(worlds).forEach(w=>w.root.visible=false);},pause(){paused=true;},resume(){paused=false;},setScene(type){if(!Object.values(SceneType).includes(type))throw new Error(`Unknown scene: ${type}`);manager.setScene(type,active);elapsed=0;},get canvas(){return renderer.domElement;},dispose(){renderer.setAnimationLoop(null);observer.disconnect();document.documentElement.removeEventListener('wonderlandthemechange',applyLighting);renderer.domElement.removeEventListener('webglcontextlost',lost);Object.values(worlds).forEach(w=>w.dispose());renderer.dispose();renderer.domElement.remove();}};}
export function cameraErrorMessage(error){switch(error.name){case'NotAllowedError':return'カメラを許可してください。';case'NotFoundError':return'カメラが見つかりません。';case'NotReadableError':return'カメラを使用できません。';default:return'カメラを起動できませんでした。HTTPSのSafariまたはChromeで開いてください。';}}
