const NEUTRAL=Object.freeze({name:'Neutral',saturation:1,contrast:1,brightness:1,sepia:0,hue:0,overlay:[0,0,0],overlayOpacity:0,centerOpacity:0,vignette:.06,haze:0});
export const CAMERA_FILTERS=Object.freeze({
  world01:{name:'DREAM FALL',saturation:.91,contrast:.97,brightness:1.01,sepia:.025,hue:-7,overlay:[91,116,139],overlayOpacity:.035,centerOpacity:0,vignette:.075,haze:.015},
  world02:{name:'CRIMSON GARDEN',saturation:1.13,contrast:1.08,brightness:1.005,sepia:.08,hue:-7,overlay:[120,0,20],overlayOpacity:.14,centerOpacity:.045,vignette:.12,haze:.006},
  world03:{name:'TIME SHIFT',saturation:.88,contrast:1.08,brightness:1.01,sepia:.015,hue:-7,overlay:[112,138,160],overlayOpacity:.032,centerOpacity:0,vignette:.09,haze:.008},
  world04:{name:'TEA DREAM',saturation:1.06,contrast:.96,brightness:1.055,sepia:.055,hue:-5,overlay:[231,183,169],overlayOpacity:.035,centerOpacity:0,vignette:.055,haze:.035}
});

const keys=['saturation','contrast','brightness','sepia','hue','overlayOpacity','centerOpacity','vignette','haze'];
const mix=(a,b,t)=>a+(b-a)*t;
const smooth=t=>t*t*(3-2*t);
function interpolate(from,to,t){const state={name:to.name,overlay:from.overlay.map((value,i)=>Math.round(mix(value,to.overlay[i],t)))};keys.forEach(key=>state[key]=mix(from[key],to[key],t));return state;}
export const TIME_FILTER_MODIFIERS=Object.freeze({morning:{intensity:.88,brightness:.012,sepia:-.008,hue:1},day:{intensity:1,brightness:0,sepia:0,hue:0},evening:{intensity:1.02,brightness:.004,sepia:.014,hue:-1},night:{intensity:1.07,brightness:.012,sepia:.006,hue:0}});
export function applyTimeToFilter(filter,themeName='day'){const modifier=TIME_FILTER_MODIFIERS[themeName]||TIME_FILTER_MODIFIERS.day,grade={...filter,overlay:[...filter.overlay]};for(const key of ['saturation','contrast'])grade[key]=mix(1,filter[key],modifier.intensity);for(const key of ['overlayOpacity','centerOpacity','vignette','haze'])grade[key]=filter[key]*modifier.intensity;grade.brightness=Math.min(1.08,filter.brightness+modifier.brightness);grade.sepia=Math.max(0,filter.sepia+modifier.sepia);grade.hue=filter.hue+modifier.hue;return grade;}
export function cssFilter(state,intensity=1){return`saturate(${mix(1,state.saturation,intensity).toFixed(3)}) contrast(${mix(1,state.contrast,intensity).toFixed(3)}) brightness(${mix(1,state.brightness,intensity).toFixed(3)}) sepia(${(state.sepia*intensity).toFixed(3)}) hue-rotate(${(state.hue*intensity).toFixed(2)}deg)`;}
function overlayBackground(state,intensity=1){const [r,g,b]=state.overlay,amount=state.overlayOpacity*intensity,center=(state.centerOpacity||0)*intensity,vignette=state.vignette*intensity,haze=state.haze*intensity;return`radial-gradient(ellipse at 50% 49%, rgba(${r},${g},${b},${center.toFixed(3)}) 28%, rgba(${r},${g},${b},${Math.max(center,amount*.42).toFixed(3)}) 61%, rgba(${r},${g},${b},${amount.toFixed(3)}) 100%), radial-gradient(ellipse at center, rgba(255,244,229,${haze.toFixed(3)}) 0%, rgba(255,244,229,0) 58%), radial-gradient(ellipse at center, transparent 48%, rgba(7,8,9,${vignette.toFixed(3)}) 100%)`;}
export function createCameraFilterController(video,overlay,{duration=750,intensity=1}={}){let current={...NEUTRAL,overlay:[...NEUTRAL.overlay]},target=current,frame=0,started=0,from=current,worldId=null,themeName='day';function render(state){video.style.filter=cssFilter(state,intensity);overlay.style.background=overlayBackground(state,intensity);overlay.dataset.filter=state.name;overlay.dataset.timeTheme=themeName;}function transition(next,immediate=false){cancelAnimationFrame(frame);from=current;target=next;if(immediate){current={...next,overlay:[...next.overlay]};render(current);return;}started=performance.now();frame=requestAnimationFrame(tick);}function tick(now){const t=Math.min(1,(now-started)/duration),e=smooth(t);current=interpolate(from,target,e);render(current);if(t<1)frame=requestAnimationFrame(tick);else frame=0;}render(current);return{setWorld(nextWorldId,{immediate=false}={}){worldId=nextWorldId;transition(applyTimeToFilter(CAMERA_FILTERS[worldId]||NEUTRAL,themeName),immediate);},setTimeTheme(nextTheme,{immediate=false}={}){themeName=nextTheme?.name||nextTheme||'day';if(worldId)transition(applyTimeToFilter(CAMERA_FILTERS[worldId]||NEUTRAL,themeName),immediate);},get current(){return current;},get intensity(){return intensity;},dispose(){cancelAnimationFrame(frame);video.style.filter='';overlay.style.background='';}};}
export function applyCameraGradeOverlay(ctx,width,height,state,intensity=1){const [r,g,b]=state.overlay,amount=state.overlayOpacity*intensity,center=(state.centerOpacity||0)*intensity,vignette=state.vignette*intensity,haze=state.haze*intensity;ctx.save();ctx.globalCompositeOperation='soft-light';const atmosphere=ctx.createRadialGradient(width*.5,height*.49,Math.min(width,height)*.2,width*.5,height*.49,Math.max(width,height)*.72);atmosphere.addColorStop(0,`rgba(${r},${g},${b},${center})`);atmosphere.addColorStop(.62,`rgba(${r},${g},${b},${Math.max(center,amount*.42)})`);atmosphere.addColorStop(1,`rgba(${r},${g},${b},${amount})`);ctx.fillStyle=atmosphere;ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='screen';const soft=ctx.createRadialGradient(width*.5,height*.45,0,width*.5,height*.45,Math.max(width,height)*.55);soft.addColorStop(0,`rgba(255,244,229,${haze})`);soft.addColorStop(1,'rgba(255,244,229,0)');ctx.fillStyle=soft;ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='source-over';const shade=ctx.createRadialGradient(width*.5,height*.5,Math.min(width,height)*.32,width*.5,height*.5,Math.max(width,height)*.72);shade.addColorStop(0,'rgba(7,8,9,0)');shade.addColorStop(1,`rgba(7,8,9,${vignette})`);ctx.fillStyle=shade;ctx.fillRect(0,0,width,height);ctx.restore();}
export{NEUTRAL as NEUTRAL_CAMERA_FILTER};
