import * as THREE from 'three';
export const wrapAngle=angle=>Math.atan2(Math.sin(angle),Math.cos(angle));
export function createInteraction(surface,onModeChange=()=>{}){
  const euler=new THREE.Euler(0,0,0,'YXZ'),quaternion=new THREE.Quaternion(),correction=new THREE.Quaternion(-Math.sqrt(.5),0,0,Math.sqrt(.5)),screenCorrection=new THREE.Quaternion(),forward=new THREE.Vector3(),zAxis=new THREE.Vector3(0,0,1);
  let enabled=false,mode='touch',baseline=null,yaw=0,pitch=0,offsetYaw=0,offsetPitch=0,pointer=null,lastSensorAt=0,startedAt=0,touched=false;
  const position=new THREE.Vector3(),velocity=new THREE.Vector3(),rad=THREE.MathUtils.degToRad;
  function setMode(next){if(mode!==next){mode=next;onModeChange(mode);}}
  function orientation(event){if(!enabled||![event.alpha,event.beta,event.gamma].every(Number.isFinite))return;euler.set(rad(event.beta),rad(event.alpha),-rad(event.gamma),'YXZ');quaternion.setFromEuler(euler).multiply(correction);screenCorrection.setFromAxisAngle(zAxis,-rad(window.screen.orientation?.angle??window.orientation??0));quaternion.multiply(screenCorrection);forward.set(0,0,-1).applyQuaternion(quaternion);const sample={yaw:Math.atan2(-forward.x,-forward.z),pitch:Math.asin(THREE.MathUtils.clamp(forward.y,-1,1))};lastSensorAt=performance.now();if(!baseline){baseline=sample;offsetYaw=yaw;offsetPitch=pitch;}yaw=offsetYaw+wrapAngle(sample.yaw-baseline.yaw);pitch=THREE.MathUtils.clamp(offsetPitch+sample.pitch-baseline.pitch,rad(-78),rad(82));setMode('sensor');}
  function motion(event){if(!enabled||mode!=='sensor')return;const a=event.acceleration;if(!a||![a.x,a.y,a.z].every(Number.isFinite))return;const dt=Math.min((event.interval||16)/1000,.04);velocity.x=THREE.MathUtils.clamp((velocity.x+a.x*dt*.018)*.9,-.08,.08);velocity.y=THREE.MathUtils.clamp((velocity.y+a.y*dt*.012)*.9,-.05,.05);position.x=THREE.MathUtils.clamp(position.x+velocity.x*dt,-.16,.16);position.y=THREE.MathUtils.clamp(position.y+velocity.y*dt,-.1,.1);}
  function rebase(){baseline=null;offsetYaw=yaw;offsetPitch=pitch;}
  function down(event){if(!enabled||event.target.closest('button')||(mode==='sensor'&&performance.now()-lastSensorAt<2500))return;setMode('touch');touched=true;pointer={id:event.pointerId,x:event.clientX,y:event.clientY};surface.setPointerCapture?.(event.pointerId);}
  function move(event){if(!pointer||pointer.id!==event.pointerId)return;yaw+=(event.clientX-pointer.x)/Math.max(surface.clientWidth,1)*1.5;pitch=THREE.MathUtils.clamp(pitch+(event.clientY-pointer.y)/Math.max(surface.clientHeight,1)*2,rad(-78),rad(82));pointer.x=event.clientX;pointer.y=event.clientY;baseline=null;}
  function up(){pointer=null;}
  window.addEventListener('deviceorientation',orientation);window.addEventListener('devicemotion',motion);window.addEventListener('orientationchange',rebase);window.screen.orientation?.addEventListener('change',rebase);surface.addEventListener('pointerdown',down);surface.addEventListener('pointermove',move);surface.addEventListener('pointerup',up);surface.addEventListener('pointercancel',up);
  return{async requestPermission(){try{const orientationResult=typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'?await DeviceOrientationEvent.requestPermission():'granted';if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')await DeviceMotionEvent.requestPermission();return orientationResult;}catch{return'denied';}},get current(){return{yaw,pitch,x:position.x,y:position.y,z:position.z};},start(){enabled=true;yaw=0;pitch=0;position.set(0,0,0);velocity.set(0,0,0);baseline=null;lastSensorAt=0;touched=false;startedAt=performance.now();setMode('pending');},update(){if(enabled&&mode!=='touch'&&performance.now()-(lastSensorAt||startedAt)>2500)setMode('touch');if(enabled&&mode==='touch'&&!touched&&!pointer&&lastSensorAt===0){const t=(performance.now()-startedAt)/1000;yaw=Math.sin(t*.12)*.035;pitch=Math.cos(t*.1)*.016;}return this.current;},stop(){enabled=false;pointer=null;baseline=null;}}
}
