import {createARLayer,cameraErrorMessage} from './ar.js';
import {createInteraction} from './interaction.js';
const $=s=>document.querySelector(s),video=$('#camera'),landing=$('#landing'),select=$('#scene-select'),hud=$('#hud'),status=$('#status'),surface=$('#experience'),guide=$('#look-guide'),label=$('#scene-label'),preview=$('#photo-preview'),photo=$('#captured-photo'),flash=$('#flash');
const labels={clock:['01 /','CLOCK'],cards:['02 /','CARDS'],chess:['03 /','CHESS'],'tea-party':['04 /','TEA PARTY']};let layer,stream,generation=0,guideTimers=[],latestBlob,latestUrl,facing='environment';const interaction=createInteraction(surface);
function ensureLayer(){if(!layer)layer=createARLayer($('#ar-layer'),()=>stop('3D表示が中断されました。'),interaction);}
function stopTracks(){stream?.getTracks().forEach(t=>t.stop());stream=null;video.pause();video.srcObject=null;}
function stop(message=''){generation++;guideTimers.forEach(clearTimeout);guideTimers=[];interaction.stop();stopTracks();layer?.stop();document.body.classList.remove('active');hud.hidden=true;preview.hidden=true;select.hidden=false;status.textContent=message;}
async function openCamera(request){stopTracks();const next=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1080}}});if(request!==generation){next.getTracks().forEach(t=>t.stop());return false;}stream=next;video.srcObject=stream;await video.play();return true;}
function runGuide(){guide.classList.remove('out');const cues=[['LOOK AROUND',0],['LOOK ABOVE',1200],['LOOK BEHIND',2200],['LOOK BELOW',3200]];cues.forEach(([text,delay])=>guideTimers.push(setTimeout(()=>{guide.querySelector('strong').textContent=text;guide.querySelector('pre').hidden=text!=='LOOK AROUND';},delay)));guideTimers.push(setTimeout(()=>guide.classList.add('out'),4200));}
$('#enter').addEventListener('click',()=>{landing.hidden=true;select.hidden=false;});
async function start(type){if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){status.textContent='HTTPSのSafariまたはChromeで開いてください。';return;}const request=++generation;select.hidden=true;try{ensureLayer();await interaction.requestPermission();if(!await openCamera(request))return;const [number,name]=labels[type];label.innerHTML=`<small>${number}</small> ${name}`;layer.setScene(type);interaction.start();layer.start();hud.hidden=false;document.body.classList.add('active');runGuide();}catch(error){stop(cameraErrorMessage(error));}}
document.querySelectorAll('[data-scene]').forEach(button=>button.addEventListener('click',()=>{button.style.backgroundColor=button.dataset.scene==='cards'?'#650b12':'#11100e';setTimeout(()=>start(button.dataset.scene),300);}));
function drawCover(ctx,source,sw,sh,w,h){const scale=Math.max(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(source,(w-dw)/2,(h-dh)/2,dw,dh);}
function capture(){if(!stream||!video.videoWidth)return;flash.classList.remove('fire');void flash.offsetWidth;flash.classList.add('fire');const rect=surface.getBoundingClientRect(),ratio=Math.min(2,1600/Math.max(rect.width,rect.height)),canvas=document.createElement('canvas');canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');drawCover(ctx,video,video.videoWidth,video.videoHeight,canvas.width,canvas.height);ctx.drawImage(layer.canvas,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(!blob)return;latestBlob=blob;if(latestUrl)URL.revokeObjectURL(latestUrl);latestUrl=URL.createObjectURL(blob);photo.src=latestUrl;hud.hidden=true;preview.hidden=false;},'image/png');}
async function save(){if(!latestBlob)return;const file=new File([latestBlob],`wonderland-${Date.now()}.png`,{type:'image/png'});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Wonderland'});return;}}catch(error){if(error.name==='AbortError')return;}const a=document.createElement('a');a.href=latestUrl;a.download=file.name;a.click();}
$('#shutter').addEventListener('click',capture);$('#retake').addEventListener('click',()=>{preview.hidden=true;hud.hidden=false;});$('#save-photo').addEventListener('click',save);$('#exit').addEventListener('click',()=>stop());window.addEventListener('pagehide',()=>{stopTracks();if(latestUrl)URL.revokeObjectURL(latestUrl);});
