import * as THREE from 'three';

export const WonderlandColors={ink:0x171417,ivory:0xeee4cf,paper:0xe4d5b6,gold:0xb88b4d,darkGold:0x76552f,heart:0x9f263a,aliceBlue:0x78aebd,dustyBlue:0x527c87,emerald:0x30584c,burgundy:0x6d2633};

function canvasTexture(width,height,paint){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');paint(context,width,height);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}

const porcelainProfile=[[0,0],[.11,0],[.135,.025],[.15,.075],[.17,.16],[.185,.225]];
export function createTeaCup(variant=0){const root=new THREE.Group();root.name='CupRoot';const pattern=canvasTexture(512,256,(x,w,h)=>{x.fillStyle='#e8d8c1';x.fillRect(0,0,w,h);x.strokeStyle='#791f31';x.lineWidth=5;for(let i=0;i<7;i++){const px=35+i*75,py=85+(i%2)*55;x.beginPath();x.arc(px,py,14,0,Math.PI*2);x.stroke();x.beginPath();x.moveTo(px,py+14);x.lineTo(px-8,py+35);x.stroke();}x.strokeStyle='#a77d42';x.lineWidth=7;x.strokeRect(0,6,w,h-12);});const porcelain=new THREE.MeshStandardMaterial({map:pattern,color:0xe8d8c1,roughness:.64,metalness:.02,side:THREE.DoubleSide});const plain=new THREE.MeshStandardMaterial({color:0xe8d8c1,roughness:.68,metalness:0});const gold=new THREE.MeshStandardMaterial({color:0xa77d42,roughness:.58,metalness:.18});const cup=new THREE.Mesh(new THREE.LatheGeometry(porcelainProfile.map(([a,b])=>new THREE.Vector2(a,b)),40),porcelain);cup.name='Cup';const rim=new THREE.Mesh(new THREE.TorusGeometry(.185,.007,8,40),gold);rim.name='CupRim';rim.rotation.x=Math.PI/2;rim.position.y=.225;const handleCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(.165,.175,0),new THREE.Vector3(.275,.19,0),new THREE.Vector3(.31,.11,0),new THREE.Vector3(.265,.045,0),new THREE.Vector3(.158,.07,0)]),handleGeometry=new THREE.TubeGeometry(handleCurve,24,.017,10,false),handle=new THREE.Mesh(handleGeometry,plain);handle.name='CupHandle';handle.userData.attachmentPoints=[handleCurve.points[0].clone(),handleCurve.points.at(-1).clone()];const saucer=new THREE.Mesh(new THREE.LatheGeometry([[0,0],[.13,0],[.24,.012],[.275,.028],[.27,.04]].map(([a,b])=>new THREE.Vector2(a,b)),40),plain);saucer.name='Saucer';saucer.position.y=-.03;const opening=new THREE.Object3D();opening.name='CupOpening';opening.position.y=.225;root.add(cup,rim,handle,saucer,opening);root.userData.opening=opening;root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}

export function createTeapot(){const root=new THREE.Group(),lidRoot=new THREE.Group(),porcelain=new THREE.MeshStandardMaterial({color:0xe8d8c1,roughness:.64,metalness:.02}),gold=new THREE.MeshStandardMaterial({color:0xa77d42,roughness:.58,metalness:.18});root.name='TeapotRoot';lidRoot.name='LidRoot';const profile=[[0,-.16],[.12,-.15],[.23,-.1],[.28,.02],[.27,.14],[.19,.22],[.105,.24]];const bodyGeometry=new THREE.LatheGeometry(profile.map(([x,y])=>new THREE.Vector2(x,y)),40);bodyGeometry.computeBoundingBox();const body=new THREE.Mesh(bodyGeometry,porcelain);body.name='Body';const lidProfile=[[0,0],[.13,0],[.17,.03],[.1,.06],[0,.08]],lid=new THREE.Mesh(new THREE.LatheGeometry(lidProfile.map(([x,y])=>new THREE.Vector2(x,y)),32),porcelain);lid.name='Lid';const finial=new THREE.Mesh(new THREE.SphereGeometry(.038,18,12),gold);finial.name='Knob';finial.position.y=.105;lidRoot.position.y=.228;lidRoot.add(lid,finial);const spoutCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(.225,.035,0),new THREE.Vector3(.35,.075,0),new THREE.Vector3(.46,.19,0),new THREE.Vector3(.51,.285,0)]);const spoutGeometry=new THREE.TubeGeometry(spoutCurve,28,.054,12,false);spoutGeometry.computeBoundingBox();const spout=new THREE.Mesh(spoutGeometry,porcelain);spout.name='Spout';const handleCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-.225,.16,0),new THREE.Vector3(-.43,.2,0),new THREE.Vector3(-.49,.04,0),new THREE.Vector3(-.42,-.12,0),new THREE.Vector3(-.225,-.09,0)]);const handleGeometry=new THREE.TubeGeometry(handleCurve,32,.032,12,false);handleGeometry.computeBoundingBox();const handle=new THREE.Mesh(handleGeometry,porcelain);handle.name='Handle';const pourOrigin=new THREE.Object3D();pourOrigin.name='PourOrigin';pourOrigin.position.set(.51,.285,0);root.add(body,lidRoot,spout,handle,pourOrigin);root.userData.pourOrigin=pourOrigin;root.userData.attachmentBounds={body:bodyGeometry.boundingBox.clone(),spout:spoutGeometry.boundingBox.clone(),handle:handleGeometry.boundingBox.clone()};root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}

export function createPocketClock(hour=10,minute=6){
 const root=new THREE.Group(),faceGroup=new THREE.Group();root.name='ClockRoot';faceGroup.name='ClockFaceGroup';
 const metal=new THREE.MeshStandardMaterial({color:0x71695e,metalness:.58,roughness:.4,emissive:0x241e18,emissiveIntensity:.12}),innerMetal=new THREE.MeshStandardMaterial({color:0xb19a72,metalness:.5,roughness:.42,emissive:0x3b2915,emissiveIntensity:.1}),ivory=new THREE.MeshBasicMaterial({color:0xe8dfc5}),ink=new THREE.MeshBasicMaterial({color:0x26252a,depthTest:true,depthWrite:false});[metal,innerMetal,ivory,ink].forEach(material=>material.userData.preserveColor=true);
 const body=new THREE.Mesh(new THREE.CylinderGeometry(.245,.245,.055,40),metal);body.name='ClockCase';body.rotation.x=Math.PI/2;const outerRim=new THREE.Mesh(new THREE.TorusGeometry(.23,.025,9,40),metal);outerRim.name='OuterRim';outerRim.position.z=.03;const innerRim=new THREE.Mesh(new THREE.TorusGeometry(.205,.008,7,40),innerMetal);innerRim.name='InnerRim';innerRim.position.z=.048;
 const face=new THREE.Mesh(new THREE.CircleGeometry(.2,40),ivory);face.name='ClockFace';face.position.z=.041;face.renderOrder=1;root.add(body,outerRim,innerRim,face,faceGroup);
 const markerGeometry=new THREE.BoxGeometry(.012,.032,.006);for(let i=0;i<12;i++){const marker=new THREE.Mesh(markerGeometry,ink),angle=i*Math.PI/6;marker.name=`HourMark-${i+1}`;marker.position.set(Math.sin(angle)*.166,Math.cos(angle)*.166,.05);marker.rotation.z=-angle;marker.renderOrder=2;faceGroup.add(marker);}
 const minuteAngle=minute/60*Math.PI*2,hourAngle=(hour%12+minute/60)/12*Math.PI*2;[['MinuteHandPivot',.145,.018,minuteAngle,'minute',.062],['HourHandPivot',.105,.027,hourAngle,'hour',.059]].forEach(([name,length,width,angle,kind,z])=>{const pivot=new THREE.Group();pivot.name=name;pivot.position.z=z;pivot.rotation.z=-angle;pivot.userData.clockHand=kind;pivot.userData.baseAngle=-angle;const geometry=new THREE.BoxGeometry(width,length,.008);geometry.translate(0,length/2,0);const hand=new THREE.Mesh(geometry,ink);hand.name=kind==='minute'?'MinuteHand':'HourHand';hand.renderOrder=3;pivot.add(hand);faceGroup.add(pivot);});
 const pin=new THREE.Mesh(new THREE.SphereGeometry(.019,12,8),innerMetal);pin.name='CenterPin';pin.position.z=.064;pin.renderOrder=4;const loop=new THREE.Mesh(new THREE.TorusGeometry(.058,.015,8,24),metal);loop.name='ClockLoop';loop.position.y=.292;const crown=new THREE.Mesh(new THREE.CylinderGeometry(.025,.036,.052,12),innerMetal);crown.name='ClockCrown';crown.position.y=.245;root.add(pin,loop,crown);root.userData.clockFaceGroup=faceGroup;return root;
}

export function createDrinkMeBottle(variant=0){const colors=[0x64a8c7,0x8cc9c4,0xa78bbe,0xc98a46,0xb76d78],tone=colors[variant%colors.length],root=new THREE.Group(),glass=new THREE.MeshPhysicalMaterial({color:0xd5eef0,transparent:true,opacity:.48,roughness:.12,metalness:0,transmission:.12,emissive:0x4b7478,emissiveIntensity:.22,side:THREE.DoubleSide}),liquid=new THREE.MeshStandardMaterial({color:tone,transparent:true,opacity:.94,roughness:.34,emissive:tone,emissiveIntensity:.24}),cork=new THREE.MeshStandardMaterial({color:0x846c47,roughness:.9});root.name='PotionRoot';[glass,liquid,cork].forEach(material=>material.userData.preserveColor=true);const shoulder=new THREE.Mesh(new THREE.SphereGeometry(.09,20,12),glass);shoulder.name='GlassBottle';shoulder.scale.y=1.18;shoulder.position.y=.115;const fill=new THREE.Mesh(new THREE.SphereGeometry(.07,18,10),liquid);fill.scale.set(1,.62+(variant%4)*.05,1);fill.name='PotionLiquid';fill.position.y=.09;fill.userData.baseY=fill.position.y;const neck=new THREE.Mesh(new THREE.CylinderGeometry(.038,.052,.13,18),glass);neck.name='BottleNeck';neck.position.y=.275;const stopper=new THREE.Mesh(new THREE.CylinderGeometry(.041,.037,.055,12),cork);stopper.name='Cork';stopper.position.y=.37;const highlight=new THREE.Mesh(new THREE.CapsuleGeometry(.008,.11,3,8),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.48}));highlight.name='GlassHighlight';highlight.position.set(-.055,.135,.075);highlight.rotation.z=.15;const labelMap=canvasTexture(256,150,(x,w,h)=>{x.fillStyle='#e8dcc1';x.fillRect(0,0,w,h);x.strokeStyle='#7c3040';x.lineWidth=8;x.strokeRect(5,5,w-10,h-10);x.fillStyle='#2a2220';x.textAlign='center';x.font='bold 38px Georgia';x.fillText('DRINK',w/2,58);x.fillText('ME',w/2,108);});const label=new THREE.Mesh(new THREE.PlaneGeometry(.135,.08),new THREE.MeshBasicMaterial({map:labelMap}));label.name='DrinkMeLabel';label.position.set(0,.15,.091);label.material.userData.preserveColor=true;root.add(shoulder,fill,neck,stopper,highlight,label);root.userData.liquid=fill;root.userData.potionColor=tone;return root;}

export function createEatMeSweet(variant=0){
 const baked=[0xc99555,0xd3a46a,0xb98245],tone=baked[variant%3],root=new THREE.Group(),cake=new THREE.MeshStandardMaterial({color:tone,roughness:.88,emissive:tone,emissiveIntensity:.2}),edge=new THREE.MeshStandardMaterial({color:0x8d5a32,roughness:.94,emissive:0x39200f,emissiveIntensity:.18});root.name='EatMeSweet';cake.userData.preserveColor=edge.userData.preserveColor=true;
 const biscuit=new THREE.Mesh(new THREE.CylinderGeometry(.155,.155,.058,variant%3===0?20:28),cake);biscuit.name='BiscuitBody';biscuit.rotation.x=Math.PI/2;if(variant%3===2)biscuit.scale.set(1.28,.78,1);const rim=new THREE.Mesh(new THREE.TorusGeometry(.13,.012,7,28),edge);rim.name='BiscuitRim';rim.position.z=.032;if(variant%3===2)rim.scale.set(1.25,.78,1);root.add(biscuit,rim);const dimpleGeometry=new THREE.SphereGeometry(.009,6,4),dimpleMaterial=new THREE.MeshBasicMaterial({color:0x754628});dimpleMaterial.userData.preserveColor=true;for(let i=0;i<8;i++){const a=i*Math.PI/4,dimple=new THREE.Mesh(dimpleGeometry,dimpleMaterial);dimple.name=`BiscuitDimple-${i}`;dimple.scale.y=.45;dimple.position.set(Math.cos(a)*.095*(variant%3===2?1.24:1),Math.sin(a)*.095*(variant%3===2?.76:1),.034);root.add(dimple);}if(variant%3===1){const icing=createHeart();icing.name='IcingHeart';icing.scale.setScalar(.34);icing.position.z=.04;icing.material.color.setHex(0xd9a0a7);icing.material.userData.preserveColor=true;root.add(icing);}
 const map=canvasTexture(256,96,(x,w,h)=>{x.fillStyle='#efe3ca';x.fillRect(0,0,w,h);x.strokeStyle='#8b5d43';x.lineWidth=7;x.strokeRect(5,5,w-10,h-10);x.fillStyle='#6e2834';x.textAlign='center';x.textBaseline='middle';x.font='bold 34px Georgia';x.fillText('EAT ME',w/2,h/2+2);}),labelMaterial=new THREE.MeshBasicMaterial({map,transparent:true}),label=new THREE.Mesh(new THREE.PlaneGeometry(.17,.065),labelMaterial);labelMaterial.userData.preserveColor=true;label.name='EatMeLabel';label.position.set(0,0,.043);root.add(label);return root;
}

export function createHeart(){const shape=new THREE.Shape();shape.moveTo(0,-.13);shape.bezierCurveTo(-.24,.03,-.18,.22,0,.12);shape.bezierCurveTo(.18,.22,.24,.03,0,-.13);return new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.025,bevelEnabled:true,bevelSize:.01,bevelThickness:.01}),new THREE.MeshStandardMaterial({color:WonderlandColors.heart,roughness:.45}));}

export function createPlayingCard(suit='♥',value='Q'){
 const root=new THREE.Group();
 const face=canvasTexture(320,440,(x,w,h)=>{x.fillStyle='#efe5d4';x.fillRect(0,0,w,h);x.strokeStyle='#5b0b18';x.lineWidth=8;x.strokeRect(10,10,w-20,h-20);x.fillStyle=['♥','♦'].includes(suit)?'#99162b':'#171417';x.font='bold 58px Georgia';x.fillText(value,25,68);x.textAlign='center';x.font='135px Georgia';x.fillText(suit,w/2,h/2+48);});
 const body=new THREE.Mesh(new THREE.BoxGeometry(.4,.52,.025),new THREE.MeshStandardMaterial({color:0xd7c9b2,roughness:.68})),front=new THREE.Mesh(new THREE.PlaneGeometry(.385,.505),new THREE.MeshBasicMaterial({map:face}));front.position.z=.013;root.add(body,front);return root;
}
export function createGear(radius=.34,teeth=12,color=0x9a7448){const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,metalness:.42,roughness:.6});const ring=new THREE.Mesh(new THREE.TorusGeometry(radius*.7,radius*.12,8,teeth*2),mat);group.add(ring);for(let i=0;i<teeth;i++){const tooth=new THREE.Mesh(new THREE.BoxGeometry(radius*.18,radius*.17,.08),mat),a=i*Math.PI*2/teeth;tooth.position.set(Math.cos(a)*radius*.89,Math.sin(a)*radius*.89,0);tooth.rotation.z=a;group.add(tooth);}for(let i=0;i<6;i++){const spoke=new THREE.Mesh(new THREE.BoxGeometry(radius*.68,.035,.055),mat);spoke.rotation.z=i*Math.PI/3;group.add(spoke);}return group;}
export function createRose(){
 const group=new THREE.Group(),colors=[0x9b2940,0x781329,0x570c1a,0x3b0812],materials=colors.map((color,index)=>new THREE.MeshStandardMaterial({color,roughness:.76+index*.035,metalness:0}));group.name='RoseRoot';
 const layers=[{count:9,radius:.125,size:.112,z:0},{count:7,radius:.088,size:.09,z:.038},{count:5,radius:.052,size:.067,z:.074},{count:3,radius:.023,size:.048,z:.108}];
 layers.forEach((layer,layerIndex)=>{const geometry=new THREE.SphereGeometry(layer.size,10,7,0,Math.PI*2,0,Math.PI*.58);for(let i=0;i<layer.count;i++){const jitter=1+((i*7+layerIndex*3)%5-2)*.035,a=i*Math.PI*2/layer.count+layerIndex*.51+(i%2?.06:-.035),petal=new THREE.Mesh(geometry,materials[layerIndex]);petal.scale.set(jitter,.38+(i%3)*.025,.68+(i%2)*.06);petal.position.set(Math.cos(a)*layer.radius*jitter,Math.sin(a)*layer.radius*(.82+(i%2)*.08),layer.z+(i%3)*.004);petal.rotation.set(.5+layerIndex*.07,a+.28,(i%3-1)*.08);group.add(petal);}});
 const heart=new THREE.Mesh(new THREE.SphereGeometry(.036,10,7),materials[3]);heart.scale.set(.72,.72,1.18);heart.position.z=.135;group.add(heart);return group;
}
export function createKey(){const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:WonderlandColors.gold,metalness:.55,roughness:.48}),ring=new THREE.Mesh(new THREE.TorusGeometry(.07,.014,7,20),mat),stem=new THREE.Mesh(new THREE.BoxGeometry(.025,.24,.025),mat),tooth=new THREE.Mesh(new THREE.BoxGeometry(.09,.025,.025),mat);stem.position.y=-.16;tooth.position.set(.035,-.27,0);group.add(ring,stem,tooth);return group;}
