import * as THREE from 'three';

export const WonderlandColors={ink:0x171417,ivory:0xeee4cf,paper:0xe4d5b6,gold:0xb88b4d,darkGold:0x76552f,heart:0x9f263a,aliceBlue:0x78aebd,dustyBlue:0x527c87,emerald:0x30584c,burgundy:0x6d2633};

function canvasTexture(width,height,paint){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');paint(context,width,height);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}

export function createTeaCup(variant=0){const root=new THREE.Group();const pattern=canvasTexture(512,256,(x,w,h)=>{x.fillStyle='#eee5d6';x.fillRect(0,0,w,h);x.fillStyle='#8ab7c5';for(let i=0;i<12;i++)x.fillRect(i*w/12,0,variant%2?7:12,h);x.fillStyle='#a43b50';for(let i=0;i<9;i++){x.beginPath();x.arc(38+i*57,80+(i%2)*68,6,0,Math.PI*2);x.fill();}x.strokeStyle='#b78a49';x.lineWidth=8;x.strokeRect(0,5,w,h-10);});const porcelain=new THREE.MeshStandardMaterial({map:pattern,color:WonderlandColors.ivory,roughness:.48,metalness:.02,side:THREE.DoubleSide});const plain=new THREE.MeshStandardMaterial({color:WonderlandColors.ivory,roughness:.48});const gold=new THREE.MeshStandardMaterial({color:WonderlandColors.gold,roughness:.38,metalness:.55});const cup=new THREE.Mesh(new THREE.CylinderGeometry(.18,.135,.21,32,1,true),porcelain);cup.position.y=.1;const bottom=new THREE.Mesh(new THREE.CylinderGeometry(.135,.135,.018,32),plain);const rim=new THREE.Mesh(new THREE.TorusGeometry(.18,.009,8,32),gold);rim.rotation.x=Math.PI/2;rim.position.y=.205;const handle=new THREE.Mesh(new THREE.TorusGeometry(.085,.018,10,24,Math.PI*1.5),plain);handle.rotation.z=Math.PI/2;handle.position.set(.18,.11,0);handle.scale.y=1.2;const saucer=new THREE.Mesh(new THREE.CylinderGeometry(.27,.24,.025,32),plain);saucer.position.y=-.03;root.add(cup,bottom,rim,handle,saucer);return root;}

export function createPocketClock(hour=10,minute=6){const root=new THREE.Group();const gold=new THREE.MeshStandardMaterial({color:WonderlandColors.gold,metalness:.68,roughness:.32});const outer=new THREE.Mesh(new THREE.CylinderGeometry(.24,.24,.045,40),gold);outer.rotation.x=Math.PI/2;root.add(outer);const faceMap=canvasTexture(512,512,(x,w,h)=>{x.fillStyle='#efe3c9';x.fillRect(0,0,w,h);x.fillStyle='#211b19';x.textAlign='center';x.textBaseline='middle';x.font='26px Georgia';const roman=['XII','I','II','III','IV','V','VI','VII','VIII','IX','X','XI'];for(let i=0;i<12;i++){const a=i*Math.PI/6-Math.PI/2;x.fillText(roman[i],w/2+Math.cos(a)*190,h/2+Math.sin(a)*190);}});const face=new THREE.Mesh(new THREE.CircleGeometry(.205,40),new THREE.MeshBasicMaterial({map:faceMap}));face.position.z=.024;root.add(face);const handMat=new THREE.MeshBasicMaterial({color:WonderlandColors.ink});const minuteAngle=minute/60*Math.PI*2,hourAngle=(hour%12+minute/60)/12*Math.PI*2;for(const[length,width,angle]of[[.15,.012,minuteAngle],[.11,.018,hourAngle]]){const hand=new THREE.Mesh(new THREE.PlaneGeometry(width,length),handMat);hand.position.set(Math.sin(angle)*length/2,Math.cos(angle)*length/2,.03);hand.rotation.z=-angle;root.add(hand);}const loop=new THREE.Mesh(new THREE.TorusGeometry(.055,.014,8,20),gold);loop.position.y=.285;root.add(loop);const crown=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.05,12),gold);crown.position.y=.24;root.add(crown);return root;}

export function createChessPiece(type='pawn',color=WonderlandColors.ivory){const root=new THREE.Group(),material=new THREE.MeshStandardMaterial({color,roughness:.35,metalness:.04});const cylinder=(rt,rb,h,y)=>{const mesh=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,24),material);mesh.position.y=y;root.add(mesh);};cylinder(.16,.21,.08,.04);cylinder(.08,.135,.26,.2);if(type==='rook'){cylinder(.15,.11,.14,.39);for(let i=0;i<4;i++){const tooth=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,.08),material);tooth.position.set(Math.cos(i*Math.PI/2)*.1,.5,Math.sin(i*Math.PI/2)*.1);root.add(tooth);}}else if(type==='king'||type==='queen'){const crown=new THREE.Mesh(new THREE.ConeGeometry(type==='king'?.12:.15,.18,type==='king'?4:8),material);crown.position.y=.43;root.add(crown);if(type==='king'){const bar=new THREE.Mesh(new THREE.BoxGeometry(.16,.025,.025),material);bar.position.y=.55;root.add(bar);}}else{const head=new THREE.Mesh(new THREE.SphereGeometry(.1,18,14),material);head.position.y=.38;root.add(head);}return root;}

export function createDrinkMeBottle(){const root=new THREE.Group(),glass=new THREE.MeshPhysicalMaterial({color:0xbad7d9,transparent:true,opacity:.62,roughness:.1,transmission:.25}),liquid=new THREE.MeshStandardMaterial({color:0xb65b67,transparent:true,opacity:.75}),cork=new THREE.MeshStandardMaterial({color:0x846c47,roughness:.9});const body=new THREE.Mesh(new THREE.CylinderGeometry(.065,.085,.22,18),glass);body.position.y=.11;const fill=new THREE.Mesh(new THREE.CylinderGeometry(.055,.072,.11,18),liquid);fill.position.y=.065;const neck=new THREE.Mesh(new THREE.CylinderGeometry(.035,.05,.1,18),glass);neck.position.y=.27;const stopper=new THREE.Mesh(new THREE.CylinderGeometry(.038,.038,.045,12),cork);stopper.position.y=.345;const labelMap=canvasTexture(256,150,(x,w,h)=>{x.fillStyle='#e8dcc1';x.fillRect(0,0,w,h);x.strokeStyle='#846c47';x.lineWidth=8;x.strokeRect(5,5,w-10,h-10);x.fillStyle='#2a2220';x.textAlign='center';x.font='bold 38px Georgia';x.fillText('DRINK',w/2,58);x.fillText('ME',w/2,108);});const label=new THREE.Mesh(new THREE.PlaneGeometry(.13,.075),new THREE.MeshBasicMaterial({map:labelMap}));label.position.set(0,.15,.078);root.add(body,fill,neck,stopper,label);return root;}

export function createHeart(){const shape=new THREE.Shape();shape.moveTo(0,-.13);shape.bezierCurveTo(-.24,.03,-.18,.22,0,.12);shape.bezierCurveTo(.18,.22,.24,.03,0,-.13);return new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.025,bevelEnabled:true,bevelSize:.01,bevelThickness:.01}),new THREE.MeshStandardMaterial({color:WonderlandColors.heart,roughness:.45}));}
