import * as THREE from 'three';
import {createVictorianChessPiece} from './chess.js';

export const WonderlandColors={ink:0x171417,ivory:0xeee4cf,paper:0xe4d5b6,gold:0xb88b4d,darkGold:0x76552f,heart:0x9f263a,aliceBlue:0x78aebd,dustyBlue:0x527c87,emerald:0x30584c,burgundy:0x6d2633};

function canvasTexture(width,height,paint){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');paint(context,width,height);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}

const porcelainProfile=[[0,0],[.11,0],[.135,.025],[.15,.075],[.17,.16],[.185,.225]];
export function createTeaCup(variant=0){const root=new THREE.Group();const pattern=canvasTexture(512,256,(x,w,h)=>{x.fillStyle='#e8d8c1';x.fillRect(0,0,w,h);x.strokeStyle='#791f31';x.lineWidth=5;for(let i=0;i<7;i++){const px=35+i*75,py=85+(i%2)*55;x.beginPath();x.arc(px,py,14,0,Math.PI*2);x.stroke();x.beginPath();x.moveTo(px,py+14);x.lineTo(px-8,py+35);x.stroke();}x.strokeStyle='#a77d42';x.lineWidth=7;x.strokeRect(0,6,w,h-12);});const porcelain=new THREE.MeshStandardMaterial({map:pattern,color:0xe8d8c1,roughness:.64,metalness:.02,side:THREE.DoubleSide});const plain=new THREE.MeshStandardMaterial({color:0xe8d8c1,roughness:.68,metalness:0});const gold=new THREE.MeshStandardMaterial({color:0xa77d42,roughness:.58,metalness:.18});const cup=new THREE.Mesh(new THREE.LatheGeometry(porcelainProfile.map(([a,b])=>new THREE.Vector2(a,b)),40),porcelain);const rim=new THREE.Mesh(new THREE.TorusGeometry(.185,.007,8,40),gold);rim.rotation.x=Math.PI/2;rim.position.y=.225;const handle=new THREE.Mesh(new THREE.TorusGeometry(.085,.015,10,28,Math.PI*1.55),plain);handle.rotation.z=Math.PI/2;handle.position.set(.185,.12,0);handle.scale.y=1.25;const saucer=new THREE.Mesh(new THREE.LatheGeometry([[0,0],[.13,0],[.24,.012],[.275,.028],[.27,.04]].map(([a,b])=>new THREE.Vector2(a,b)),40),plain);saucer.position.y=-.03;root.add(cup,rim,handle,saucer);root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}

export function createTeapot(){const root=new THREE.Group(),porcelain=new THREE.MeshStandardMaterial({color:0xe8d8c1,roughness:.64,metalness:.02}),gold=new THREE.MeshStandardMaterial({color:0xa77d42,roughness:.58,metalness:.18});root.name='TeaPotGroup';const profile=[[0,-.16],[.12,-.15],[.23,-.1],[.28,.02],[.27,.14],[.19,.22],[.105,.24]];const body=new THREE.Mesh(new THREE.LatheGeometry(profile.map(([x,y])=>new THREE.Vector2(x,y)),40),porcelain);body.name='Body';const lid=new THREE.Mesh(new THREE.LatheGeometry([[0,.235],[.13,.235],[.17,.27],[.1,.3],[0,.32]].map(([x,y])=>new THREE.Vector2(x,y)),32),porcelain);lid.name='Lid';const finial=new THREE.Mesh(new THREE.SphereGeometry(.035,18,12),gold);finial.name='Knob';finial.position.y=.345;const spoutCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(.255,.045,0),new THREE.Vector3(.37,.09,0),new THREE.Vector3(.47,.2,0),new THREE.Vector3(.5,.29,0)]);const spout=new THREE.Mesh(new THREE.TubeGeometry(spoutCurve,24,.052,12,false),porcelain);spout.name='Spout';const handle=new THREE.Mesh(new THREE.TorusGeometry(.2,.03,12,36,Math.PI*1.48),porcelain);handle.name='Handle';handle.rotation.z=-Math.PI/2;handle.position.set(-.205,.075,0);const pourOrigin=new THREE.Object3D();pourOrigin.name='PourOrigin';pourOrigin.position.set(.505,.292,0);root.add(body,lid,finial,spout,handle,pourOrigin);root.userData.pourOrigin=pourOrigin;root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}

export function createPocketClock(hour=10,minute=6){const root=new THREE.Group();const gold=new THREE.MeshStandardMaterial({color:0x9a7448,metalness:.54,roughness:.52});const rim=new THREE.Mesh(new THREE.TorusGeometry(.225,.026,8,36),gold);rim.position.z=.025;const outer=new THREE.Mesh(new THREE.CylinderGeometry(.24,.24,.045,40),gold);outer.rotation.x=Math.PI/2;root.add(outer,rim);const faceMap=canvasTexture(512,512,(x,w,h)=>{const g=x.createRadialGradient(w*.45,h*.4,20,w/2,h/2,w*.58);g.addColorStop(0,'#f3ead6');g.addColorStop(.78,'#dfcfad');g.addColorStop(1,'#b99d73');x.fillStyle=g;x.fillRect(0,0,w,h);x.strokeStyle='rgba(88,63,38,.25)';x.lineWidth=3;for(let i=0;i<14;i++){x.beginPath();x.arc(w/2,h/2,70+i*11,0,Math.PI*2);x.stroke();}x.fillStyle='#211b19';x.textAlign='center';x.textBaseline='middle';x.font='26px Georgia';const roman=['XII','I','II','III','IV','V','VI','VII','VIII','IX','X','XI'];for(let i=0;i<12;i++){const a=i*Math.PI/6-Math.PI/2;x.fillText(roman[i],w/2+Math.cos(a)*190,h/2+Math.sin(a)*190);}});const face=new THREE.Mesh(new THREE.CircleGeometry(.205,40),new THREE.MeshBasicMaterial({map:faceMap}));face.position.z=.026;root.add(face);const handMat=new THREE.MeshBasicMaterial({color:WonderlandColors.ink});const minuteAngle=minute/60*Math.PI*2,hourAngle=(hour%12+minute/60)/12*Math.PI*2;[['minute',.15,.012,minuteAngle],['hour',.11,.018,hourAngle]].forEach(([kind,length,width,angle])=>{const hand=new THREE.Mesh(new THREE.PlaneGeometry(width,length),handMat);hand.position.set(Math.sin(angle)*length/2,Math.cos(angle)*length/2,.032);hand.rotation.z=-angle;hand.userData.clockHand=kind;hand.userData.baseAngle=-angle;root.add(hand);});const pin=new THREE.Mesh(new THREE.SphereGeometry(.018,10,7),gold);pin.position.z=.036;const loop=new THREE.Mesh(new THREE.TorusGeometry(.055,.014,8,20),gold);loop.position.y=.285;const crown=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.05,12),gold);crown.position.y=.24;root.add(pin,loop,crown);return root;}

export function createChessPiece(type='pawn',color=WonderlandColors.ivory){return createVictorianChessPiece(type,color);}

export function createDrinkMeBottle(){const root=new THREE.Group(),glass=new THREE.MeshPhysicalMaterial({color:0xbad7d9,transparent:true,opacity:.62,roughness:.1,transmission:.25}),liquid=new THREE.MeshStandardMaterial({color:0xb65b67,transparent:true,opacity:.75}),cork=new THREE.MeshStandardMaterial({color:0x846c47,roughness:.9});const body=new THREE.Mesh(new THREE.CylinderGeometry(.065,.085,.22,18),glass);body.position.y=.11;const fill=new THREE.Mesh(new THREE.CylinderGeometry(.055,.072,.11,18),liquid);fill.position.y=.065;const neck=new THREE.Mesh(new THREE.CylinderGeometry(.035,.05,.1,18),glass);neck.position.y=.27;const stopper=new THREE.Mesh(new THREE.CylinderGeometry(.038,.038,.045,12),cork);stopper.position.y=.345;const labelMap=canvasTexture(256,150,(x,w,h)=>{x.fillStyle='#e8dcc1';x.fillRect(0,0,w,h);x.strokeStyle='#846c47';x.lineWidth=8;x.strokeRect(5,5,w-10,h-10);x.fillStyle='#2a2220';x.textAlign='center';x.font='bold 38px Georgia';x.fillText('DRINK',w/2,58);x.fillText('ME',w/2,108);});const label=new THREE.Mesh(new THREE.PlaneGeometry(.13,.075),new THREE.MeshBasicMaterial({map:labelMap}));label.position.set(0,.15,.078);root.add(body,fill,neck,stopper,label);return root;}

export function createHeart(){const shape=new THREE.Shape();shape.moveTo(0,-.13);shape.bezierCurveTo(-.24,.03,-.18,.22,0,.12);shape.bezierCurveTo(.18,.22,.24,.03,0,-.13);return new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.025,bevelEnabled:true,bevelSize:.01,bevelThickness:.01}),new THREE.MeshStandardMaterial({color:WonderlandColors.heart,roughness:.45}));}

export function createPlayingCard(suit='♥',value='Q'){
 const root=new THREE.Group();
 const face=canvasTexture(320,440,(x,w,h)=>{x.fillStyle='#efe5d4';x.fillRect(0,0,w,h);x.strokeStyle='#5b0b18';x.lineWidth=8;x.strokeRect(10,10,w-20,h-20);x.fillStyle=['♥','♦'].includes(suit)?'#99162b':'#171417';x.font='bold 58px Georgia';x.fillText(value,25,68);x.textAlign='center';x.font='135px Georgia';x.fillText(suit,w/2,h/2+48);});
 const body=new THREE.Mesh(new THREE.BoxGeometry(.4,.52,.025),new THREE.MeshStandardMaterial({color:0xd7c9b2,roughness:.68})),front=new THREE.Mesh(new THREE.PlaneGeometry(.385,.505),new THREE.MeshBasicMaterial({map:face}));front.position.z=.013;root.add(body,front);return root;
}
export function createGear(radius=.34,teeth=12,color=0x9a7448){const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,metalness:.42,roughness:.6});const ring=new THREE.Mesh(new THREE.TorusGeometry(radius*.7,radius*.12,8,teeth*2),mat);group.add(ring);for(let i=0;i<teeth;i++){const tooth=new THREE.Mesh(new THREE.BoxGeometry(radius*.18,radius*.17,.08),mat),a=i*Math.PI*2/teeth;tooth.position.set(Math.cos(a)*radius*.89,Math.sin(a)*radius*.89,0);tooth.rotation.z=a;group.add(tooth);}for(let i=0;i<6;i++){const spoke=new THREE.Mesh(new THREE.BoxGeometry(radius*.68,.035,.055),mat);spoke.rotation.z=i*Math.PI/3;group.add(spoke);}return group;}
export function createRose(color=0x9a0a24){const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,roughness:.78});for(let layer=0;layer<3;layer++)for(let i=0;i<6;i++){const petal=new THREE.Mesh(new THREE.SphereGeometry(.105-layer*.018,8,5),mat),a=i*Math.PI/3+layer*.35;petal.scale.set(1.25,.5,.62);petal.position.set(Math.cos(a)*(.1-layer*.02),Math.sin(a)*(.075-layer*.015),layer*.025);petal.rotation.z=a;group.add(petal);}return group;}
export function createKey(){const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:WonderlandColors.gold,metalness:.55,roughness:.48}),ring=new THREE.Mesh(new THREE.TorusGeometry(.07,.014,7,20),mat),stem=new THREE.Mesh(new THREE.BoxGeometry(.025,.24,.025),mat),tooth=new THREE.Mesh(new THREE.BoxGeometry(.09,.025,.025),mat);stem.position.y=-.16;tooth.position.set(.035,-.27,0);group.add(ring,stem,tooth);return group;}
