import * as THREE from 'three';
import {createDoor} from './door.js';
import {WonderlandState} from './scenes.js';
import {WonderlandColors,createTeaCup,createPocketClock,createChessPiece,createDrinkMeBottle,createHeart} from './objects.js';
const smooth=t=>t*t*(3-2*t),suits=['♥','♦','♣','♠'],values=['A','2','3','4','5','6','7','8','9','10','J','Q'];
function texture(suit,value){const c=document.createElement('canvas');c.width=256;c.height=356;const x=c.getContext('2d');x.fillStyle='#eee4cf';x.fillRect(0,0,256,356);x.strokeStyle='#b88b4d';x.lineWidth=6;x.strokeRect(5,5,246,346);x.fillStyle=suit==='♥'||suit==='♦'?'#9f263a':'#171417';x.font='bold 42px Georgia';x.fillText(value,18,48);x.fillText(suit,18,91);x.font='82px Georgia';x.textAlign='center';x.fillText(suit,128,215);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function createCards(){const root=new THREE.Group(),items=[],geometry=new THREE.PlaneGeometry(.28,.4),positions=[[-1.28,.83,-1.8,1.55],[1.3,.92,-2,1.45],[-1.35,-.4,-2.5,1.15],[1.36,-.28,-2.7,1.05],[-1.2,.25,-3.4,.8],[1.08,.34,-3.6,.75],[-.9,1.23,-4,.7],[.82,1.34,-4.5,.65],[-1.55,.1,-5,.6],[1.52,-.05,-5.2,.58],[-1.05,1.5,-5.6,.55],[1.12,1.52,-5.9,.55]];positions.forEach((p,i)=>{const card=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({map:texture(suits[i%4],values[i]),side:THREE.DoubleSide}));card.userData.base=new THREE.Vector3(p[0],p[1],p[2]);card.userData.finalScale=p[3];card.userData.phase=i*.73;card.userData.speed=.22+(i%3)*.07;root.add(card);items.push(card);});return{root,items};}
function particles(){const count=20,p=new Float32Array(count*3);for(let i=0;i<count;i++){p[i*3]=Math.sin(i*9.7)*2;p[i*3+1]=-.7+i%7*.35;p[i*3+2]=-2-i%5*.7;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color:WonderlandColors.gold,size:.025,transparent:true,opacity:.62,depthWrite:false}));}
function at(object,x,y,z,scale=1){object.position.set(x,y,z);object.scale.setScalar(scale);object.userData.base=object.position.clone();object.userData.baseScale=object.scale.clone();return object;}
export function createWonderlandObjects(){
 const root=new THREE.Group(),cards=createCards(),door=createDoor();door.setOpenAmount(.08);
 const clocks=[at(createPocketClock(10,6),-1.15,.95,-3.3,1.15),at(createPocketClock(3,47),1.12,.6,-4.2,.75),at(createPocketClock(11,53),.72,1.28,-5,.82),at(createPocketClock(1,20),-1.48,.18,-5.4,.6)];clocks[1].scale.set(.58,.9,.75);clocks[2].rotation.z=-.28;clocks[3].scale.set(.75,.49,.6);clocks.forEach(o=>o.userData.baseScale=o.scale.clone());
 const cups=[at(createTeaCup(0),1.05,-.78,-2.8,.72),at(createTeaCup(1),-1.3,-.62,-4,.58),at(createTeaCup(2),1.35,-.28,-5,.5)];
 const chess=[at(createChessPiece('pawn'),-1.05,-1.16,-3,.9),at(createChessPiece('queen',WonderlandColors.ink),.78,-1.18,-3.7,1.05),at(createChessPiece('rook'),-1.45,-1.2,-4.3,.8),at(createChessPiece('king',WonderlandColors.ink),1.35,-1.18,-4.7,.82),at(createChessPiece('pawn',WonderlandColors.ink),.98,-1.25,-5.3,.65)];
 const bottles=[at(createDrinkMeBottle(),-.92,-.85,-3.2,1.15),at(createDrinkMeBottle(),1.5,-.92,-4.8,.8)];const hearts=[at(createHeart(),1.42,1.16,-3.8,.7),at(createHeart(),-1.42,.5,-4.7,.5),at(createHeart(),1.6,.2,-5.6,.38)];const dust=particles();door.root.position.set(0,-.85,-3.2);root.add(cards.root,door.root,...clocks,...cups,...chess,...bottles,...hearts,dust);
 const all=[...clocks,...cups,...chess,...bottles,...hearts],hideAll=()=>{cards.items.forEach(o=>o.visible=false);all.forEach(o=>o.visible=false);door.root.visible=false;dust.visible=false;};
 function restore(o){o.position.copy(o.userData.base);if(o.userData.baseScale)o.scale.copy(o.userData.baseScale);else o.scale.setScalar(o.userData.finalScale);}
 function reset(){root.visible=false;hideAll();cards.items.forEach(o=>{o.position.copy(o.userData.base);o.scale.setScalar(o.userData.finalScale);o.rotation.set(0,0,0);});all.forEach(restore);}
 function reveal(list,count){list.forEach((o,i)=>o.visible=i<count);}
 function update(state,age,elapsed,reduced){root.visible=true;hideAll();
  if(state===WonderlandState.NORMAL)return;
  if(state===WonderlandState.GROWING){const p=smooth(Math.min(age/3,1)),scale=THREE.MathUtils.lerp(1,.2,p);reveal(cards.items,2);reveal(clocks,1);reveal(cups,1);reveal(chess,1);[cards.items[0],cards.items[1],clocks[0],cups[0],chess[0]].forEach(o=>{restore(o);o.scale.multiplyScalar(scale);o.position.z-=p*2;});return;}
  if(state===WonderlandState.GIANT){door.root.visible=true;door.root.scale.setScalar(.2);reveal(clocks,1);reveal(cups,1);reveal(chess,1);[clocks[0],cups[0],chess[0]].forEach(o=>{restore(o);o.scale.multiplyScalar(.2);o.position.z-=2;});return;}
  const p=state===WonderlandState.SHRINKING?smooth(Math.min(age/3,1)):1;reveal(cards.items,state===WonderlandState.SHRINKING?6:state===WonderlandState.TINY?6:12);reveal(clocks,state===WonderlandState.SHRINKING?2:state===WonderlandState.TINY?3:4);reveal(cups,state===WonderlandState.SHRINKING?1:state===WonderlandState.TINY?2:3);reveal(chess,state===WonderlandState.SHRINKING?2:state===WonderlandState.TINY?4:5);reveal(bottles,state===WonderlandState.SHRINKING?0:state===WonderlandState.TINY?1:2);reveal(hearts,state===WonderlandState.WONDERLAND?3:1);dust.visible=state===WonderlandState.GRAVITY_BREAK||state===WonderlandState.WONDERLAND;
  cards.items.forEach((o,i)=>{o.position.copy(o.userData.base);o.scale.setScalar(o.userData.finalScale*THREE.MathUtils.lerp(.25,1,p));if(state===WonderlandState.GRAVITY_BREAK||state===WonderlandState.WONDERLAND){const lift=state===WonderlandState.GRAVITY_BREAK?Math.max(0,(age-.3)/1.7):1;o.position.y+=Math.min(lift,1)*.16;if(!reduced){o.position.x+=Math.sin(elapsed*o.userData.speed+o.userData.phase)*.18;o.position.y+=Math.sin(elapsed*.45+o.userData.phase)*.05;o.rotation.z=Math.sin(elapsed*.3+o.userData.phase)*.18;}}});
  all.forEach(restore);if(state===WonderlandState.SHRINKING)all.filter(o=>o.visible).forEach(o=>o.scale.multiplyScalar(THREE.MathUtils.lerp(.25,1,p)));if(!reduced){clocks.forEach((o,i)=>o.rotation.z=(i===2?-.28:0)+Math.sin(elapsed*.32+i)*.04);cups.forEach((o,i)=>o.rotation.z=Math.sin(elapsed*.38+i)*.06);bottles.forEach((o,i)=>o.position.y=o.userData.base.y+Math.sin(elapsed*.65+i)*.04);}dust.rotation.y=reduced?0:elapsed*.025;
 }
 reset();return{root,reset,update};
}
