import * as THREE from 'three';
import {createHeart,createPlayingCard,createRose} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference,plane,texture} from './composition.js';
import {upgradeWithModel} from './asset-loader.js';
import {WORLD_CONFIGS} from './world-config.js';

function crimsonHaze(){return texture(256,256,(x,w,h)=>{const g=x.createRadialGradient(w/2,h/2,10,w/2,h/2,w/2);g.addColorStop(0,'rgba(120,0,24,.3)');g.addColorStop(.55,'rgba(92,0,20,.24)');g.addColorStop(1,'rgba(45,0,12,0)');x.fillStyle=g;x.fillRect(0,0,w,h);});}
export function createWorld02(){
 const root=new THREE.Group(),{background,midground,foreground}=createDepthLayers(root),cards=[],roses=[],hearts=[],animated=[],visit=createVisitVariation(3),motion=motionPreference();root.name='QueensCourtRoot';root.userData.definition=WORLD_CONFIGS.world02;
 const haze=plane(crimsonHaze(),5.5,4.1,{opacity:.68,depth:'far'});haze.position.set(0,.1,-7);background.add(haze);
 const courtLight=new THREE.PointLight(0xd4b37a,.48,7,2);courtLight.position.set(-1.4,1.8,-1.2);root.add(courtLight);
 const cardFrame=[[-.88,1.05,-4.5,-.12],[.88,1,-4.7,.1],[-1.02,.3,-4.1,-.18],[1.02,.25,-4.3,.16],[-.92,-.62,-4.4,-.08],[.92,-.58,-4.6,.09],[0,1.45,-5.1,0]];
 for(let i=0;i<7;i++){const[x,y,z,rotation]=cardFrame[i],card=new THREE.Group(),isNear=i===4||i===5;card.add(createPlayingCard(i%3===0?'♦':i===6?'♠':'♥',i===0?'Q':String((i%8)+2)));card.position.set(x,y,isNear?-1.55:z);card.rotation.z=rotation;card.scale.setScalar(isNear?.44:.58-(i%3)*.035);card.userData={base:card.position.clone(),baseRotation:rotation,phase:i*.91+.4,priority:i>5?3:1,depth:isNear?'near':'mid',baseScale:card.scale.x,speed:.18+i*.017,amplitudeX:.045+(i%3)*.018,amplitudeY:.025+(i%2)*.016};(isNear?foreground:midground).add(card);cards.push(card);animated.push(card);upgradeWithModel(card,'playingCard',{scale:isNear?.42:.55});}
 [[-1.12,.55,-6,1.7],[1.12,.48,-6.3,1.5]].forEach(([x,y,z,s],i)=>{const heart=createHeart();heart.position.set(x,y,z);heart.scale.setScalar(s);heart.rotation.z=i?-.16:.18;heart.traverse(object=>{if(object.material){object.material=object.material.clone();object.material.color?.setHex(i?0x71091f:0x4f0616);object.material.transparent=true;object.material.opacity=.28;object.material.depthWrite=false;}});heart.userData={base:heart.position.clone(),phase:i,priority:2,depth:'far'};background.add(heart);hearts.push(heart);animated.push(heart);});
 const roseColors=[0x8f0b25,0x5b0719,0xa30d2d,0x6f0b1d];[[-.55,-.82,-2.25,.82],[.55,-.78,-2.5,.78],[-1.05,.42,-3.6,.72],[1.05,.5,-3.8,.68]].forEach(([x,y,z,s],i)=>{const rose=new THREE.Group(),flower=createRose(roseColors[i]);rose.add(flower);rose.position.set(x,y,z);rose.scale.setScalar(s);rose.userData={base:rose.position.clone(),baseScale:s,priority:i>1?2:1,depth:z>-3?'near':'mid',phase:Math.random()*Math.PI*2};(z>-3?foreground:midground).add(rose);roses.push(rose);animated.push(rose);});
 const goldGeometry=new THREE.BufferGeometry(),goldPoints=[];for(let i=0;i<12;i++)goldPoints.push(((i*37)%101)/48-1.05,((i*61)%97)/42-.9,-4.8-(i%3));goldGeometry.setAttribute('position',new THREE.Float32BufferAttribute(goldPoints,3));const goldDust=new THREE.Points(goldGeometry,new THREE.PointsMaterial({color:0xd4b37a,size:.018,transparent:true,opacity:.28,depthWrite:false}));background.add(goldDust);
 let theme=null;function update(time,delta,{view={yaw:0,pitch:0},theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed,photoMoment=motion.events&&elapsed>=3&&elapsed<=5?Math.sin((elapsed-3)/2*Math.PI):0,yaw=THREE.MathUtils.clamp(view.yaw||0,-.38,.38),pitch=THREE.MathUtils.clamp(view.pitch||0,-.28,.28),variant=visit.variant;cards.forEach((card,i)=>{const u=card.userData,side=Math.sign(u.base.x),flowX=Math.sin(t*u.speed+u.phase)*u.amplitudeX,flowY=Math.cos(t*(u.speed*.73)+u.phase)*u.amplitudeY,m=microMotion(t,{phase:u.phase,duration:6+i*.45,float:.012*motion.scale,rotate:.025*motion.scale,scale:.006*motion.scale});card.position.set(u.base.x+flowX+side*photoMoment*(u.depth==='near'?.11:.08)-yaw*(u.depth==='near'?.13:.07),u.base.y+flowY+m.y-pitch*(u.depth==='near'?.08:.055),u.base.z+Math.sin(t*.11+u.phase)*.035);card.rotation.set(Math.sin(t*.13+u.phase)*.08,m.rotation*(i%2?-1:1),u.baseRotation+m.rotation);card.scale.setScalar(u.baseScale*(variant===0?m.scale:1));});roses.forEach((rose,i)=>{const u=rose.userData,m=microMotion(t,{phase:u.phase,duration:7+i*.6,float:.026*motion.scale,rotate:.025*motion.scale,scale:.018*motion.scale}),open=1+photoMoment*(i<2?.07:.045);rose.position.x=u.base.x-yaw*(u.depth==='near'?.18:.1);rose.position.y=u.base.y+m.y-pitch*.09;rose.scale.setScalar(u.baseScale*m.scale*open);rose.rotation.z=m.rotation;});hearts.forEach((heart,i)=>{const m=microMotion(t,{phase:heart.userData.phase,duration:9+i,float:.018*motion.scale,rotate:.01*motion.scale,scale:.01*motion.scale});heart.position.x=heart.userData.base.x-yaw*.04;heart.position.y=heart.userData.base.y+m.y-pitch*.035;heart.visible=variant!==1||i===0;});haze.material.opacity=.7+(active.name==='night'?.12:.04);goldDust.rotation.z=Math.sin(t*.08)*.025;goldDust.material.opacity=.22*(active.particleOpacity??1);}
 function responsive(width,height){const spread=width/height>1?1.25:width/height<.62?.9:1;roses.forEach(r=>{if(r.userData.originalX===undefined)r.userData.originalX=r.userData.base.x;r.userData.base.x=r.userData.originalX*spread;});applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world02',{tint:.28});},responsive,reset(){visit.reset();animated.forEach(o=>o.userData.base&&o.position.copy(o.userData.base));},dispose(){disposeRoot(root);}};
}
