import * as THREE from 'three';
import {createPlayingCard,createRose,createTeaCup,createTeapot} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference} from './composition.js';
import {upgradeWithModel} from './asset-loader.js';
import {WORLD_CONFIGS} from './world-config.js';

export const TEA_PARALLAX=Object.freeze({far:.20,mid:.50,near:.90});
const PARALLAX_RANGE=.22;

function dessert(color=0xc98793){const group=new THREE.Group(),plate=new THREE.Mesh(new THREE.CylinderGeometry(.22,.24,.025,20),new THREE.MeshStandardMaterial({color:0xeee4d3,roughness:.6})),cake=new THREE.Mesh(new THREE.CylinderGeometry(.13,.15,.17,20),new THREE.MeshStandardMaterial({color,roughness:.72}));cake.position.y=.1;group.add(plate,cake);return group;}
export function createWorld04(){
 const root=new THREE.Group(),teaPartyRoot=new THREE.Group(),animated=[],depthObjects=[],visit=createVisitVariation(3),motion=motionPreference();teaPartyRoot.name='TeaPartyRoot';root.add(teaPartyRoot);const{background:atmosphereGroup,midground:tableGroup,foreground:teapotGroup}=createDepthLayers(teaPartyRoot);atmosphereGroup.name='background-depth';tableGroup.name='midground-depth';teapotGroup.name='foreground-depth';root.userData.definition=WORLD_CONFIGS.world04;
 const debugOcclusion=typeof location!=='undefined'&&new URLSearchParams(location.search).get('debugOcclusion')==='1';
 const table=new THREE.Mesh(new THREE.CylinderGeometry(1.25,1.34,.14,48),new THREE.MeshStandardMaterial({color:0xd2bea4,roughness:.78,metalness:0,transparent:true,opacity:.86}));table.name='TeaTable';table.position.set(0,-1.08,-3.5);table.scale.z=.58;
 tableGroup.add(table);
 const pot=new THREE.Group();pot.name='TeaPotPivot';const teaPotGroup=createTeapot();teaPotGroup.rotation.y=Math.PI;pot.add(teaPotGroup);pot.position.set(.22,-.54,-3.25);pot.scale.setScalar(.58);pot.userData={base:pot.position.clone(),phase:Math.random()*Math.PI*2,priority:1,depth:'near',parallax:TEA_PARALLAX.mid*PARALLAX_RANGE};teapotGroup.add(pot);animated.push(pot);depthObjects.push(pot);
 const cups=[[-.48,-.88,-3.28,.58],[.58,-.9,-3.48,.48]].map(([x,y,z,s],i)=>{const cup=new THREE.Group();cup.name=i?'TeaCupRight':'TeaCupLeft';cup.add(createTeaCup());cup.position.set(x,y,z);cup.scale.setScalar(s);cup.userData={base:cup.position.clone(),phase:Math.random()*Math.PI*2,priority:1,depth:'mid',parallax:TEA_PARALLAX.mid*PARALLAX_RANGE,moving:i===0};tableGroup.add(cup);animated.push(cup);depthObjects.push(cup);upgradeWithModel(cup,'teacup',{scale:.78});return cup;});const cup=cups[0];
 [[-.92,.32,-5.8,.52],[.92,.26,-6.2,.48],[-.82,-.78,-2.35,.5],[.82,-.8,-2.45,.46]].forEach(([x,y,z,s],i)=>{const flower=createRose(i%2?0xc98793:0xb97887);flower.position.set(x,y,z);flower.scale.setScalar(s);const depth=i<2?'far':'near';flower.userData={base:flower.position.clone(),baseScale:s,priority:i<2?2:1,depth,phase:Math.random()*Math.PI*2,parallax:TEA_PARALLAX[depth]*PARALLAX_RANGE,moving:i===0||i===3};(depth==='far'?atmosphereGroup:teapotGroup).add(flower);depthObjects.push(flower);animated.push(flower);});
 [[-1.02,.08,-6.4,'♥','Q',-.28],[1.02,.02,-5.8,'♠','A',.24]].forEach(([x,y,z,suit,value,rotation],i)=>{const card=createPlayingCard(suit,value);card.position.set(x,y,z);card.rotation.z=rotation;card.scale.setScalar(.32);card.userData={base:card.position.clone(),baseRotation:rotation,priority:2,depth:'far',phase:i+4,parallax:TEA_PARALLAX.far*PARALLAX_RANGE,moving:false};atmosphereGroup.add(card);depthObjects.push(card);animated.push(card);});
 const debugCard=debugOcclusion?createPlayingCard('♦','T'):null;if(debugCard){debugCard.name='occlusion-debug-card';debugCard.position.set(-1.1,0,-5.2);debugCard.scale.setScalar(.55);debugCard.userData={base:debugCard.position.clone(),priority:1,depth:'far',phase:0,parallax:TEA_PARALLAX.far*PARALLAX_RANGE};atmosphereGroup.add(debugCard);}
 [[-.72,-.96,-3.62,0xc98793],[.75,-.98,-3.55,0xd6b18b]].forEach(([x,y,z,color])=>{const cake=dessert(color);cake.position.set(x,y,z);cake.scale.setScalar(.48);cake.userData={base:cake.position.clone(),priority:2,depth:'mid',phase:6,parallax:TEA_PARALLAX.mid*PARALLAX_RANGE,moving:false};tableGroup.add(cake);depthObjects.push(cake);animated.push(cake);});
 const drops=[];for(let i=0;i<8;i++){const drop=new THREE.Mesh(new THREE.SphereGeometry(.024,6,5),new THREE.MeshBasicMaterial({color:0xd7ab72,transparent:true,opacity:0,depthWrite:false}));drop.userData.offset=i/8;teapotGroup.add(drop);drops.push(drop);}
 const steamGeometry=new THREE.BufferGeometry(),steamPositions=new Float32Array(15);steamGeometry.setAttribute('position',new THREE.BufferAttribute(steamPositions,3));const steam=new THREE.Points(steamGeometry,new THREE.PointsMaterial({color:0xf5e9dc,size:.032,transparent:true,opacity:.28,depthWrite:false}));steam.name='TeaSteam';teapotGroup.add(steam);
 const pourWorld=new THREE.Vector3(),pourLocal=new THREE.Vector3(),cupWorld=new THREE.Vector3(),cupLocal=new THREE.Vector3();let theme=null;function update(time,delta,{view={yaw:0,pitch:0},theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed,eventPhase=motion.events?elapsed%11:0,lift=eventPhase>8&&eventPhase<10?Math.sin((eventPhase-8)/2*Math.PI):0,yaw=THREE.MathUtils.clamp(view.yaw||0,-.38,.38),pitch=THREE.MathUtils.clamp(view.pitch||0,-.28,.28),variant=visit.variant;
  depthObjects.forEach((object,i)=>{const u=object.userData,parallax=u.parallax,m=microMotion(t,{phase:u.phase||i,duration:7+(i%4),float:(u.moving?(u.depth==='near'?.02:.012):0)*motion.scale,rotate:u.moving?.009*motion.scale:0,scale:u.moving?.005*motion.scale:0});object.position.x=u.base.x-yaw*parallax;object.position.y=u.base.y-pitch*parallax+m.y;if(u.baseScale)object.scale.setScalar(u.baseScale*(variant===1?m.scale:1));});
  if(debugCard)debugCard.position.x=-1.1+((t%6)/6)*2.2;
  const potMotion=microMotion(t,{phase:pot.userData.phase,duration:7,float:.012*motion.scale,rotate:.035*motion.scale,scale:0});pot.position.y=pot.userData.base.y-pitch*pot.userData.parallax+lift*.055*motion.scale;pot.rotation.z=potMotion.rotation-lift*.07*motion.scale;cup.position.y=cup.userData.base.y-pitch*cup.userData.parallax+lift*.065*motion.scale;cup.rotation.z=Math.sin(t*.55+cup.userData.phase)*.025*motion.scale;
  root.updateMatrixWorld(true);teaPotGroup.userData.pourOrigin.getWorldPosition(pourWorld);pourLocal.copy(pourWorld);teapotGroup.worldToLocal(pourLocal);drops.forEach(drop=>{const p=(eventPhase-8)/2+drop.userData.offset;if(lift>0&&variant===2){const progress=((p%1)+1)%1;drop.visible=true;drop.material.opacity=Math.sin(progress*Math.PI)*.28;drop.position.set(pourLocal.x+Math.sin(progress*Math.PI)*.02,pourLocal.y-progress*.32,pourLocal.z);}else{drop.visible=false;drop.material.opacity=0;}});cup.getWorldPosition(cupWorld);cupLocal.copy(cupWorld);teapotGroup.worldToLocal(cupLocal);steam.position.copy(cupLocal);for(let i=0;i<5;i++){const p=(t*(variant===0?.075:.055)+i/5)%1,index=i*3;steamPositions[index]=Math.sin(t*.5+i*1.9)*(.016+i*.0015)*motion.scale;steamPositions[index+1]=.15+p*.24;steamPositions[index+2]=Math.cos(t*.28+i)*.007;}steam.material.opacity=(variant===0?.3:.2)*(active.particleOpacity??1);steam.geometry.attributes.position.needsUpdate=true;
 }
 function responsive(width,height){const spread=THREE.MathUtils.clamp(width/height/.51,.9,1.45);depthObjects.forEach(object=>{if(object.userData.originalX===undefined)object.userData.originalX=object.userData.base.x;object.userData.base.x=object.userData.originalX*spread;});applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world04',{tint:.25});},responsive,reset(){visit.reset();animated.forEach(o=>o.userData.base&&o.position.copy(o.userData.base));pot.rotation.set(0,0,0);cups.forEach(item=>item.rotation.set(0,0,0));drops.forEach(drop=>{drop.visible=false;drop.material.opacity=0;});},dispose(){disposeRoot(root);}};
}
