import * as THREE from 'three';
import {createRose,createTeaCup,createTeapot} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,cycleState,disposeRoot,easeInOut} from './composition.js';
import {upgradeWithModel} from './asset-loader.js';
import {WORLD_CONFIGS} from './world-config.js';

function dessert(color=0xc98793){const group=new THREE.Group(),plate=new THREE.Mesh(new THREE.CylinderGeometry(.22,.24,.025,20),new THREE.MeshStandardMaterial({color:0xeee4d3,roughness:.6})),cake=new THREE.Mesh(new THREE.CylinderGeometry(.13,.15,.17,20),new THREE.MeshStandardMaterial({color,roughness:.72}));cake.position.y=.1;group.add(plate,cake);return group;}
export function createWorld04(){
 const root=new THREE.Group(),{background,midground,foreground}=createDepthLayers(root),animated=[],flowers=[];root.userData.definition=WORLD_CONFIGS.world04;
 const table=new THREE.Mesh(new THREE.BoxGeometry(4.7,.1,1.15),new THREE.MeshStandardMaterial({color:0xe8ddcc,roughness:.9,transparent:true,opacity:.82}));table.position.set(0,-1.2,-3.25);midground.add(table);
 const pot=new THREE.Group();pot.add(createTeapot());pot.position.set(-1.25,-.72,-2.7);pot.scale.setScalar(1.8);pot.userData={base:pot.position.clone(),priority:1,depth:'mid'};midground.add(pot);animated.push(pot);upgradeWithModel(pot,'teapot',{scale:.8});
 const cup=new THREE.Group();cup.add(createTeaCup());cup.position.set(.9,-.87,-2.45);cup.scale.setScalar(1.55);cup.userData={base:cup.position.clone(),priority:1,depth:'mid'};midground.add(cup);animated.push(cup);upgradeWithModel(cup,'teacup',{scale:.8});
 [[-1.95,-.72,-2.35,1.25],[1.88,-.68,-2.5,1.2],[-1.82,.92,-4.7,.75],[1.72,1.08,-5,.7]].forEach(([x,y,z,s],i)=>{const flower=createRose(i%2?0xd6a1aa:0xb97887);flower.position.set(x,y,z);flower.scale.setScalar(s);flower.userData={base:flower.position.clone(),priority:i>1?2:1,depth:z<-4?'far':'near',phase:i};(z<-4?background:foreground).add(flower);flowers.push(flower);animated.push(flower);});
 [[-.25,-.94,-2.8,0xc98793],[1.55,-.98,-3.1,0xd6b18b]].forEach(([x,y,z,color])=>{const cake=dessert(color);cake.position.set(x,y,z);cake.scale.setScalar(.8);midground.add(cake);});
 const drops=[];for(let i=0;i<12;i++){const drop=new THREE.Mesh(new THREE.SphereGeometry(.018,6,5),new THREE.MeshBasicMaterial({color:0xc59662,transparent:true,opacity:0,depthWrite:false}));drop.userData.offset=i/12;foreground.add(drop);drops.push(drop);}
 let theme=null;function update(time,delta,{view={yaw:0,pitch:0},theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},t=time*active.animationSpeed,state=cycleState(t,10.5,.43,.68),hero=easeInOut(state.hero),yaw=THREE.MathUtils.clamp(view.yaw||0,-.38,.38),pitch=THREE.MathUtils.clamp(view.pitch||0,-.28,.28),build=state.phase==='build'?easeInOut(state.local):state.phase==='rest'?0:1,recover=state.phase==='recovery'?1-easeInOut(state.local):1,pour=hero*recover;pot.position.set(pot.userData.base.x-yaw*.12,pot.userData.base.y+build*.18-pitch*.08,pot.userData.base.z);pot.rotation.z=-pour*.42;cup.position.set(cup.userData.base.x-yaw*.12,cup.userData.base.y+hero*.24-pitch*.08,cup.userData.base.z);cup.rotation.z=Math.sin(t*.6)*.025;drops.forEach((drop,i)=>{const p=(state.local*1.8+drop.userData.offset)%1;if(state.phase==='hero'){drop.visible=true;drop.material.opacity=Math.sin(p*Math.PI)*.75;drop.position.set(-.48+p*1.15,-.55-p*.38+Math.sin(p*Math.PI)*.08,-2.2);}else{drop.visible=false;drop.material.opacity=0;}});flowers.forEach((flower,i)=>{flower.position.x=flower.userData.base.x-yaw*(flower.userData.depth==='near'?.18:.05);flower.position.y=flower.userData.base.y+Math.sin(t*.28+flower.userData.phase)*.025-pitch*.07;flower.rotation.z=Math.sin(t*.3+i)*.035;});}
 function responsive(width,height){const spread=width/height>1?1.26:width/height<.62?.9:1;flowers.forEach(f=>{if(f.userData.originalX===undefined)f.userData.originalX=f.userData.base.x;f.userData.base.x=f.userData.originalX*spread;});applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world04',{tint:.25});},responsive,reset(){animated.forEach(o=>o.userData.base&&o.position.copy(o.userData.base));},dispose(){disposeRoot(root);}};
}
