import * as THREE from 'three';
import {createKey,createPlayingCard,createPocketClock} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference,paperTexture,plane} from './composition.js';
import {upgradeWithModel} from './asset-loader.js';
import {WORLD_CONFIGS} from './world-config.js';

export function createWorld01(){
 const root=new THREE.Group(),{background,midground,foreground}=createDepthLayers(root),fallers=[],watches=[],visit=createVisitVariation(3),motion=motionPreference();root.userData.definition=WORLD_CONFIGS.world01;
 [[-.62,.28,-3.25,1.48,0],[1.08,-.42,-4.7,.82,2.4]].forEach(([x,y,z,s,phase],i)=>{const holder=new THREE.Group(),clock=createPocketClock(i?4:10,i?43:8);holder.add(clock);holder.position.set(x,y,z);holder.scale.setScalar(s);holder.userData={base:holder.position.clone(),phase:phase+Math.random()*Math.PI*2,priority:i?2:1,depth:i?'far':'mid',watch:true,baseScale:s,spin:i?-.012:.011,hands:clock.children.filter(child=>child.userData.clockHand)};(i?background:midground).add(holder);watches.push(holder);fallers.push(holder);upgradeWithModel(holder,'pocketWatch',{scale:.75});});
 const pageMap=paperTexture('page','#342f2c');for(let i=0;i<7;i++){let object;if(i%4===0)object=createKey();else if(i%3===0)object=plane(pageMap,.28,.38,{opacity:.6,depth:'far'});else object=createPlayingCard(i%2?'♠':'♥',String((i%9)+2));const side=i%2?-1:1,z=-2.8-(i%4)*1.05;object.position.set(side*(1.15+(i%3)*.34),1.75-(i*.57%3.6),z);object.scale.setScalar(i%2?.55:.42);object.userData={base:object.position.clone(),phase:i*.73,priority:i>5?3:2,depth:z<-5?'far':'mid',moving:i%3===0};(z<-5?background:midground).add(object);fallers.push(object);}
 const dustGeo=new THREE.BufferGeometry(),points=[];for(let i=0;i<18;i++)points.push(((i*37)%101)/28-1.8,((i*67)%101)/26-1.8,-3-(i%5));dustGeo.setAttribute('position',new THREE.Float32BufferAttribute(points,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xd9c49c,size:.025,transparent:true,opacity:.38,depthWrite:false}));background.add(dust);
 let theme=null;function update(time,delta,{view={yaw:0,pitch:0},theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed,yaw=THREE.MathUtils.clamp(view.yaw||0,-.38,.38),pitch=THREE.MathUtils.clamp(view.pitch||0,-.28,.28),eventPhase=motion.events?(elapsed%12):0,surreal=eventPhase>9&&eventPhase<10.5?Math.sin((eventPhase-9)/1.5*Math.PI):0,variant=visit.variant;fallers.forEach((o,i)=>{const u=o.userData,m=microMotion(t,{phase:u.phase,duration:6.5+(i%5),float:(u.watch?.02:u.moving?.035:0)*motion.scale,rotate:(u.watch?.014:u.moving?.025:0)*motion.scale,scale:u.moving?.006*motion.scale:0});o.position.y=u.base.y+m.y-pitch*(u.depth==='near'?.15:.06);o.position.x=u.base.x+(u.watch||u.moving?Math.cos(t*.24+u.phase)*.018*motion.scale:0)-yaw*(u.depth==='near'?.2:.08);if(u.watch){o.rotation.z=m.rotation+t*u.spin*(variant===0?1.15:1);u.hands.forEach((hand,index)=>{const direction=index?-1:1,reverse=variant===1&&i===0?1-surreal*2:1;hand.rotation.z=hand.userData.baseAngle+t*(index?.035:.12)*direction*reverse*(1+surreal*2);});}else{o.rotation.x=m.rotation*.4;o.rotation.y=m.rotation*(i%2?-1:1);o.rotation.z=m.rotation;}});dust.material.opacity=(active.particleOpacity??.38)*(variant===2?1:.65);}
 function responsive(width,height){const spread=width/height>1?1.25:width/height<.62?.9:1;fallers.forEach(o=>{if(o.userData.originalX===undefined)o.userData.originalX=o.userData.base.x;o.userData.base.x=o.userData.originalX*spread;});applyResponsivePriority(fallers,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world01',{tint:.18});},responsive,reset(){visit.reset();fallers.forEach(o=>o.position.copy(o.userData.base));},dispose(){disposeRoot(root);}};
}
