import * as THREE from 'three';
import {createDrinkMeBottle,createEatMeSweet,createTeaCup} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference} from './composition.js';
import {discoveryPosition} from './discovery-ring.js';

function transformation(elapsed,phase,kind){const cycle=((elapsed+phase)%14+14)%14;if(cycle<8)return 1;const pulse=Math.sin((cycle-8)/6*Math.PI)**2;return kind==='sweet'?1+pulse*1.25:kind==='bottle'?1-pulse*.56:1;}
export function createWorld03(){
 const root=new THREE.Group(),animated=[],visit=createVisitVariation(3),motion=motionPreference(),{background,midground,foreground}=createDepthLayers(root);root.name='EatDrinkWorldRoot';root.userData.objectCount={sweets:12,bottles:8,supporting:8};
 function add(object,{name,angle,radius,y,scale,kind,index,slot}){object.name=name;object.position.copy(discoveryPosition(angle,radius,y));object.rotation.set((slot-1)*.09,THREE.MathUtils.degToRad(angle),index%2?.08:-.07);object.scale.setScalar(scale);object.userData={base:object.position.clone(),baseRotation:object.rotation.clone(),baseScale:scale,phase:index*1.17+kind.length,kind,priority:slot===2?3:2,depth:slot===0?'near':slot===2?'far':'mid'};(slot===0?foreground:slot===2?background:midground).add(object);animated.push(object);}
 for(let i=0;i<12;i++){const sector=i%8,slot=i%3;add(createEatMeSweet(i),{name:`EatMeSweet-${i}`,angle:sector*45+(slot-1)*13,radius:2.25+slot*.48,y:[.7,-.18,.38,-.55,.58,-.08,.76,-.38][sector]+slot*.18,scale:.58+slot*.08,kind:'sweet',index:i,slot});}
 for(let i=0;i<8;i++){const sector=i,slot=(i+1)%3;add(createDrinkMeBottle(),{name:`DrinkMeBottle-${i}`,angle:sector*45+17,radius:2.6+slot*.4,y:[-.18,.65,-.48,.3,-.62,.5,-.1,.72][sector],scale:.82+slot*.12,kind:'bottle',index:i+12,slot});}
 for(let i=0;i<8;i++){const sector=i,slot=i%3;add(createTeaCup(i),{name:`WonderlandCup-${i}`,angle:sector*45-16,radius:2.72+slot*.4,y:[.16,-.62,.62,-.05,.72,-.35,.32,-.7][sector],scale:.54+slot*.08,kind:'cup',index:i+20,slot});}
 let theme=null;function update(time,delta,{theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed;animated.forEach((object,i)=>{const u=object.userData,m=microMotion(t,{phase:u.phase,duration:6+i%6,float:.045*motion.scale,rotate:.035*motion.scale,scale:.018*motion.scale}),eventScale=motion.events?transformation(elapsed,u.phase,u.kind):1;object.position.y=u.base.y+m.y;object.position.x=u.base.x+Math.cos(t*.28+u.phase)*.022*motion.scale;object.rotation.x=u.baseRotation.x+m.rotation*.5;object.rotation.y=u.baseRotation.y+t*(i%2?-.022:.018)*motion.scale;object.rotation.z=u.baseRotation.z+m.rotation;object.scale.setScalar(u.baseScale*m.scale*eventScale);});}
 function responsive(width,height){applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world03',{tint:.16});},responsive,reset(){visit.reset();animated.forEach(object=>{object.position.copy(object.userData.base);object.rotation.copy(object.userData.baseRotation);object.scale.setScalar(object.userData.baseScale);});},dispose(){disposeRoot(root);}};
}
