import * as THREE from 'three';
import {createDrinkMeBottle,createEatMeSweet,createTeaCup,createTeapot} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference} from './composition.js';
import {discoveryPosition} from './discovery-ring.js';

function transformation(elapsed,phase,kind){const cycle=((elapsed+phase)%12+12)%12;if(cycle<6.8)return 1;const local=(cycle-6.8)/5.2,pulse=Math.sin(local*Math.PI)**2;return kind==='sweet'?1+pulse*2.2:kind==='bottle'?1-pulse*.7:1;}
function finishPorcelain(root,variant,{tea=false}={}){const trims=[0xd9a0a7,0x9fc1cb,0xc3a365],cream=0xf4e6d0;root.traverse(object=>{if(!object.material)return;object.material=object.material.clone();object.material.userData.preserveColor=true;const color=object.name==='CupRim'||object.name==='Knob'?trims[variant%trims.length]:cream;object.material.color?.setHex(color);if(object.material.emissive){object.material.emissive.setHex(color);object.material.emissiveIntensity=.28;}});if(tea){const material=new THREE.MeshBasicMaterial({color:0xa86f3e,transparent:true,opacity:.82,side:THREE.DoubleSide});material.userData.preserveColor=true;const surface=new THREE.Mesh(new THREE.CircleGeometry(.16,28),material);surface.name='TeaSurface';surface.rotation.x=-Math.PI/2;surface.position.y=.222;root.add(surface);}return root;}
function finishPotion(root,variant){const colors=[0xd995a5,0xa995c5,0x87c6bf,0x83b7cb,0xc78c55],ribbonMaterial=new THREE.MeshBasicMaterial({color:colors[variant%colors.length]});ribbonMaterial.userData.preserveColor=true;const ribbon=new THREE.Mesh(new THREE.TorusGeometry(.044,.006,6,18),ribbonMaterial);ribbon.name='BottleRibbon';ribbon.rotation.x=Math.PI/2;ribbon.position.y=.315;root.add(ribbon);const bottle=root.getObjectByName('GlassBottle');if(variant%4===1)bottle.scale.set(.78,1.5,.78);else if(variant%4===2)bottle.scale.set(1.1,.95,1);else if(variant%4===3)bottle.scale.set(.86,1.15,.86);return root;}
export function createWorld03(){
 const root=new THREE.Group(),animated=[],visit=createVisitVariation(3),motion=motionPreference(),{background,midground,foreground}=createDepthLayers(root);root.name='EatDrinkWorldRoot';root.userData.objectCount={sweets:8,bottles:8,cups:6,teapots:2};
 function add(object,{name,angle,radius,y,scale,kind,index,slot}){object.name=name;object.position.copy(discoveryPosition(angle,radius,y));object.rotation.set((slot-1)*.09,THREE.MathUtils.degToRad(angle),index%2?.08:-.07);object.scale.setScalar(scale);object.userData={...object.userData,base:object.position.clone(),baseRotation:object.rotation.clone(),baseScale:scale,phase:index*1.17+kind.length,kind,priority:slot===2?3:2,depth:slot===0?'near':slot===2?'far':'mid'};(slot===0?foreground:slot===2?background:midground).add(object);animated.push(object);}
 for(let i=0;i<8;i++){const sector=i,slot=i%3;add(createEatMeSweet(i),{name:`EatMeSweet-${i}`,angle:sector*45-13,radius:2.35+slot*.38,y:[.7,-.18,.38,-.55,.58,-.08,.76,-.38][sector],scale:.58+slot*.08,kind:'sweet',index:i,slot});}
 for(let i=0;i<8;i++){const sector=i,slot=(i+1)%3;add(finishPotion(createDrinkMeBottle(i),i),{name:`DrinkMeBottle-${i}`,angle:sector*45+16,radius:2.6+slot*.4,y:[-.18,.65,-.48,.3,-.62,.5,-.1,.72][sector],scale:.82+slot*.12,kind:'bottle',index:i+8,slot});}
 for(let i=0;i<6;i++){const sector=[0,1,2,3,5,6][i],slot=(i+2)%3;add(finishPorcelain(createTeaCup(i),i,{tea:true}),{name:`WonderlandCup-${i}`,angle:sector*45+2,radius:2.72+slot*.35,y:[.16,-.62,.62,-.05,-.35,.32][i],scale:.54+slot*.08,kind:'cup',index:i+16,slot});}
 [4,7].forEach((sector,i)=>{const slot=2-i;add(finishPorcelain(createTeapot(i),i),{name:`WonderlandTeapot-${i}`,angle:sector*45+2,radius:2.85+slot*.28,y:i?.48:-.18,scale:.48+i*.08,kind:'teapot',index:i+22,slot});});
 let theme=null;function update(time,delta,{theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed;animated.forEach((object,i)=>{const u=object.userData,m=microMotion(t,{phase:u.phase,duration:3.8+i%5*.55,float:.24*motion.scale,rotate:.22*motion.scale,scale:.3*motion.scale}),eventScale=motion.events?transformation(elapsed,u.phase,u.kind):1,growth=Math.max(0,eventScale-1);object.position.y=u.base.y+m.y+(u.kind==='bottle'?(1-eventScale)*.18:0);object.position.z=u.base.z-growth*.22;object.position.x=u.base.x+Math.cos(t*.38+u.phase)*.075*motion.scale;object.rotation.x=u.baseRotation.x+m.rotation*.55;object.rotation.y=u.baseRotation.y+Math.sin(t*.3+u.phase)*.16*motion.scale;object.rotation.z=u.baseRotation.z+m.rotation;object.scale.setScalar(u.baseScale*m.scale*eventScale);const liquid=object.userData.liquid||object.children.find(child=>child.name==='PotionLiquid');if(liquid){liquid.position.y=liquid.userData.baseY+Math.sin(t*1.25+u.phase)*.006;liquid.rotation.z=-m.rotation*.2;}});}
 function responsive(width,height){applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world03',{tint:.16});},responsive,reset(){visit.reset();animated.forEach(object=>{object.position.copy(object.userData.base);object.rotation.copy(object.userData.baseRotation);object.scale.setScalar(object.userData.baseScale);});},dispose(){disposeRoot(root);}};
}
