import * as THREE from 'three';
import {createKey,createPlayingCard,createPocketClock} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,cycleState,disposeRoot,easeInOut,paperTexture,plane} from './composition.js';
import {upgradeWithModel} from './asset-loader.js';
import {WORLD_CONFIGS} from './world-config.js';

export function createWorld01(){
 const root=new THREE.Group(),{background,midground,foreground}=createDepthLayers(root),fallers=[],watches=[];root.userData.definition=WORLD_CONFIGS.world01;
 [[-1.32,.35,-3.5,1.35,0],[.94,-.42,-1.9,1.55,2.4]].forEach(([x,y,z,s,phase],i)=>{const holder=new THREE.Group();holder.add(createPocketClock(i?4:10,i?43:8));holder.position.set(x,y,z);holder.scale.setScalar(s);holder.userData={base:holder.position.clone(),phase,priority:1,depth:i?'near':'mid',watch:true,baseScale:s};(i?foreground:midground).add(holder);watches.push(holder);fallers.push(holder);upgradeWithModel(holder,'pocketWatch',{scale:.75});});
 const pageMap=paperTexture('page','#342f2c');for(let i=0;i<10;i++){let object;if(i%4===0)object=createKey();else if(i%3===0)object=plane(pageMap,.28,.38,{opacity:.6,depth:'far'});else object=createPlayingCard(i%2?'♠':'♥',String((i%9)+2));const side=i%2?-1:1,z=-2.8-(i%4)*1.05;object.position.set(side*(1.15+(i%3)*.34),1.75-(i*.57%3.6),z);object.scale.setScalar(i%2?.55:.42);object.userData={base:object.position.clone(),phase:i*.73,priority:i>6?3:2,depth:z<-5?'far':'mid'};(z<-5?background:midground).add(object);fallers.push(object);}
 const dustGeo=new THREE.BufferGeometry(),points=[];for(let i=0;i<28;i++)points.push(((i*37)%101)/28-1.8,((i*67)%101)/26-1.8,-3-(i%5));dustGeo.setAttribute('position',new THREE.Float32BufferAttribute(points,3));background.add(new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xd9c49c,size:.025,transparent:true,opacity:.45,depthWrite:false})));
 let theme=null;function update(time,delta,{view={yaw:0,pitch:0},theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},t=time*active.animationSpeed,state=cycleState(t,12,.54,.76),hero=easeInOut(state.hero),yaw=THREE.MathUtils.clamp(view.yaw||0,-.38,.38),pitch=THREE.MathUtils.clamp(view.pitch||0,-.28,.28);fallers.forEach((o,i)=>{const u=o.userData,loop=((t*(.12+(i%4)*.018)+u.phase)%3.9),fall=u.watch?loop*.24:loop*.55;o.position.y=u.base.y+(u.watch?.48:1)-fall-pitch*(u.depth==='near'?.15:.06);o.position.x=u.base.x+Math.sin(t*.42+i)*(.05+(i%3)*.018)-yaw*(u.depth==='near'?.2:.08);o.rotation.x=t*(.11+(i%3)*.035);o.rotation.y=t*(.15+(i%2)*.06);o.rotation.z=Math.sin(t*.34+i)*.16;});const near=watches[1];near.position.x=near.userData.base.x-yaw*.22-hero*.26;near.position.z=near.userData.base.z+hero*.4;near.scale.setScalar(near.userData.baseScale+hero*.22);}
 function responsive(width,height){const spread=width/height>1?1.25:width/height<.62?.9:1;fallers.forEach(o=>{if(o.userData.originalX===undefined)o.userData.originalX=o.userData.base.x;o.userData.base.x=o.userData.originalX*spread;});applyResponsivePriority(fallers,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world01',{tint:.18});},responsive,reset(){fallers.forEach(o=>o.position.copy(o.userData.base));},dispose(){disposeRoot(root);}};
}
