import * as THREE from 'three';
import {createPlayingCard,createTeaCup,createTeapot} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference} from './composition.js';
import {WORLD_CONFIGS} from './world-config.js';

export const TEA_PARALLAX=Object.freeze({far:.20,mid:.50,near:.90});
const PARALLAX_RANGE=.18;
const smooth=value=>value*value*(3-2*value);
const segment=(time,start,end)=>smooth(THREE.MathUtils.clamp((time-start)/(end-start),0,1));

export function createWorld04(){
 const root=new THREE.Group(),teaPartyRoot=new THREE.Group(),animated=[],depthObjects=[],visit=createVisitVariation(3),motion=motionPreference();teaPartyRoot.name='TeaPartyRoot';root.add(teaPartyRoot);const{background,midground,foreground}=createDepthLayers(teaPartyRoot);root.userData.definition=WORLD_CONFIGS.world04;
 const pot=createTeapot();pot.position.set(-.34,.14,-3.15);pot.rotation.set(0,0,-.08);pot.scale.setScalar(.78);pot.userData={...pot.userData,base:pot.position.clone(),basePosition:pot.position.clone(),baseRotation:pot.rotation.clone(),phase:1.4,priority:1,depth:'mid',parallax:TEA_PARALLAX.mid*PARALLAX_RANGE};midground.add(pot);animated.push(pot);depthObjects.push(pot);
 const heroCup=createTeaCup();heroCup.position.set(.46,-.53,-3.05);heroCup.rotation.y=-.18;heroCup.scale.setScalar(.72);heroCup.userData={...heroCup.userData,base:heroCup.position.clone(),basePosition:heroCup.position.clone(),baseRotation:heroCup.rotation.clone(),phase:2.2,priority:1,depth:'near',parallax:TEA_PARALLAX.near*PARALLAX_RANGE};foreground.add(heroCup);animated.push(heroCup);depthObjects.push(heroCup);
 const secondCup=createTeaCup(1);secondCup.position.set(-.82,-.64,-4.15);secondCup.rotation.y=.35;secondCup.scale.setScalar(.45);secondCup.userData={...secondCup.userData,base:secondCup.position.clone(),basePosition:secondCup.position.clone(),baseRotation:secondCup.rotation.clone(),phase:4.7,priority:2,depth:'far',parallax:TEA_PARALLAX.far*PARALLAX_RANGE,moving:true};background.add(secondCup);animated.push(secondCup);depthObjects.push(secondCup);
 [[-.92,.65,-5.4,'♥','Q',-.22],[.78,.72,-5.8,'♠','A',.2],[.96,-.12,-4.7,'♦','7',-.15],[-.96,-.08,-5.1,'♣','3',.12]].forEach(([x,y,z,suit,value,rotation],i)=>{const card=createPlayingCard(suit,value);card.position.set(x,y,z);card.rotation.z=rotation;card.scale.setScalar(i<2?.32:.24);card.userData={base:card.position.clone(),baseRotation:rotation,phase:i*1.7,priority:i<2?1:2,depth:'far',parallax:TEA_PARALLAX.far*PARALLAX_RANGE,moving:true,card:true};background.add(card);animated.push(card);depthObjects.push(card);});
 const streamSections=16,streamGeometry=new THREE.BufferGeometry(),streamPositions=new Float32Array((streamSections+1)*6),streamIndices=[];for(let i=0;i<streamSections;i++){const a=i*2,b=a+1,c=a+2,d=a+3;streamIndices.push(a,c,b,b,c,d);}streamGeometry.setAttribute('position',new THREE.BufferAttribute(streamPositions,3));streamGeometry.setIndex(streamIndices);const streamMaterial=new THREE.MeshBasicMaterial({color:0xa5682f,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide});streamMaterial.userData.preserveColor=true;const stream=new THREE.Mesh(streamGeometry,streamMaterial);stream.name='TeaStream';stream.frustumCulled=false;stream.visible=false;foreground.add(stream);
 const steamGeometry=new THREE.BufferGeometry(),steamPositions=new Float32Array(15);steamGeometry.setAttribute('position',new THREE.BufferAttribute(steamPositions,3));const steam=new THREE.Points(steamGeometry,new THREE.PointsMaterial({color:0xf3e8d6,size:.03,transparent:true,opacity:.2,depthWrite:false}));steam.name='TeaSteam';foreground.add(steam);
 const pourWorld=new THREE.Vector3(),pourLocal=new THREE.Vector3(),cupWorld=new THREE.Vector3(),cupLocal=new THREE.Vector3(),control=new THREE.Vector3();let theme=null;
 function update(time,delta,{view={yaw:0,pitch:0},theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed,cycle=elapsed%10,yaw=THREE.MathUtils.clamp(view.yaw||0,-.38,.38),pitch=THREE.MathUtils.clamp(view.pitch||0,-.28,.28),rise=segment(cycle,2,3)-segment(cycle,8,9.5),tilt=segment(cycle,3,4)-segment(cycle,7,8),pour=segment(cycle,4,4.5)*(1-segment(cycle,6.3,7));
  depthObjects.forEach((object,i)=>{if(object===pot||object===heroCup)return;const u=object.userData,m=microMotion(t,{phase:u.phase||i,duration:7+(i%3),float:u.moving?.016*motion.scale:0,rotate:u.moving?.018*motion.scale:0,scale:0}),baseZ=typeof u.baseRotation==='number'?u.baseRotation:u.baseRotation?.z??0;object.position.x=u.base.x-yaw*u.parallax+(u.card?Math.sin(t*(.16+i*.018)+u.phase)*.045:0);object.position.y=u.base.y-pitch*u.parallax+m.y;object.rotation.z=baseZ+m.rotation;});
  pot.position.set(pot.userData.basePosition.x-yaw*pot.userData.parallax,pot.userData.basePosition.y-pitch*pot.userData.parallax+rise*.075*motion.scale,pot.userData.basePosition.z);pot.rotation.copy(pot.userData.baseRotation);pot.rotation.z=pot.userData.baseRotation.z-tilt*.3*motion.scale;
  heroCup.position.set(heroCup.userData.basePosition.x-yaw*heroCup.userData.parallax,heroCup.userData.basePosition.y-pitch*heroCup.userData.parallax,heroCup.userData.basePosition.z);heroCup.rotation.copy(heroCup.userData.baseRotation);
  root.updateMatrixWorld(true);pot.userData.pourOrigin.getWorldPosition(pourWorld);heroCup.userData.opening.getWorldPosition(cupWorld);pourLocal.copy(pourWorld);cupLocal.copy(cupWorld);foreground.worldToLocal(pourLocal);foreground.worldToLocal(cupLocal);control.copy(pourLocal).lerp(cupLocal,.48);control.y-=.1;const streamAttribute=streamGeometry.attributes.position;for(let i=0;i<=streamSections;i++){const p=i/streamSections,q=1-p,width=.017-i/streamSections*.005,x=q*q*pourLocal.x+2*q*p*control.x+p*p*cupLocal.x,y=q*q*pourLocal.y+2*q*p*control.y+p*p*cupLocal.y,z=q*q*pourLocal.z+2*q*p*control.z+p*p*cupLocal.z;streamAttribute.setXYZ(i*2,x-width,y,z);streamAttribute.setXYZ(i*2+1,x+width,y,z);}streamAttribute.needsUpdate=true;stream.visible=pour>.02;streamMaterial.opacity=.68*pour;
  steam.position.copy(cupLocal);for(let i=0;i<5;i++){const p=(t*.07+i/5)%1,index=i*3;steamPositions[index]=Math.sin(t*.45+i*1.7)*.018;steamPositions[index+1]=.05+p*.24;steamPositions[index+2]=Math.cos(t*.3+i)*.009;}steam.material.opacity=.22*(active.particleOpacity??1);steam.geometry.attributes.position.needsUpdate=true;
 }
 function responsive(width,height){const spread=THREE.MathUtils.clamp(width/height/.51,.9,1.3);depthObjects.forEach(object=>{if(object.userData.originalX===undefined)object.userData.originalX=object.userData.base.x;object.userData.base.x=object.userData.originalX*spread;if(object.userData.basePosition)object.userData.basePosition.x=object.userData.base.x;});applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world04',{tint:.2});},responsive,reset(){visit.reset();depthObjects.forEach(o=>o.userData.base&&o.position.copy(o.userData.base));pot.rotation.copy(pot.userData.baseRotation);heroCup.rotation.copy(heroCup.userData.baseRotation);stream.visible=false;streamMaterial.opacity=0;},dispose(){disposeRoot(root);}};
}
