import * as THREE from 'three';
import {createHeart,createPlayingCard,createRose} from '../objects.js';
import {applyResponsivePriority,applyThemeToRoot,createDepthLayers,createVisitVariation,disposeRoot,microMotion,motionPreference,plane,texture} from './composition.js';
import {upgradeWithModel} from './asset-loader.js';
import {WORLD_CONFIGS} from './world-config.js';
import {discoveryPosition} from './discovery-ring.js';

function crimsonHaze(){return texture(256,256,(x,w,h)=>{const g=x.createRadialGradient(w/2,h/2,10,w/2,h/2,w/2);g.addColorStop(0,'rgba(120,0,24,.3)');g.addColorStop(.55,'rgba(92,0,20,.24)');g.addColorStop(1,'rgba(45,0,12,0)');x.fillStyle=g;x.fillRect(0,0,w,h);});}
export function createWorld02(){
 const root=new THREE.Group(),{background,midground,foreground}=createDepthLayers(root),cards=[],roses=[],hearts=[],animated=[],visit=createVisitVariation(3),motion=motionPreference();root.name='QueensCourtRoot';root.userData.definition=WORLD_CONFIGS.world02;
 const haze=plane(crimsonHaze(),5.5,4.1,{opacity:.68,depth:'far'});haze.position.set(0,.1,-7);background.add(haze);
 const courtLight=new THREE.PointLight(0xd4b37a,.48,7,2);courtLight.position.set(-1.4,1.8,-1.2);root.add(courtLight);
 const sectorCards=[[42,2.78,.58,-.18],[91,3.02,-.08,.16],[137,2.86,.32,.2],[181,3.12,.68,-.16],[224,2.8,-.22,.12],[271,3.04,.44,-.12],[316,2.84,.08,.17]].map(([angle,radius,y,rotation])=>[...discoveryPosition(angle,radius,y),rotation,angle]),cardFrame=[[-.88,1.05,-4.5,-.12],[.88,1,-4.7,.1],[-.92,-.62,-1.55,-.08],[.92,-.58,-1.55,.09],[0,1.45,-5.1,0],...sectorCards];
 for(let i=0;i<cardFrame.length;i++){const[x,y,z,rotation,sector]=cardFrame[i],card=new THREE.Group(),isNear=i===2||i===3,isDiscovery=Number.isFinite(sector),face=createPlayingCard(i%3===0?'♦':i===4?'♠':'♥',i===0?'Q':String((i%8)+2));if(isDiscovery)face.rotation.y=THREE.MathUtils.degToRad(sector);card.name=isDiscovery?`QueenDiscovery-${sector}`:`QueenCard-${i}`;card.add(face);card.position.set(x,y,z);card.rotation.z=rotation;card.scale.setScalar(isNear?.44:isDiscovery?.34:.58-(i%3)*.035);card.userData={base:card.position.clone(),baseRotation:rotation,sector,phase:i*.91+.4,priority:isDiscovery?2:i>5?3:1,depth:isNear?'near':isDiscovery?'mid':'mid',baseScale:card.scale.x,scaleAmplitude:isNear?.025:isDiscovery?.035:.03,speed:.18+i*.017,amplitudeX:.045+(i%3)*.018,amplitudeY:.025+(i%2)*.016};(isNear?foreground:isDiscovery?background:midground).add(card);cards.push(card);animated.push(card);if(!isDiscovery)upgradeWithModel(card,'playingCard',{scale:isNear?.42:.55});}
 [[-1.12,.55,-6,1.7],[1.12,.48,-6.3,1.5]].forEach(([x,y,z,s],i)=>{const heart=createHeart();heart.position.set(x,y,z);heart.scale.setScalar(s);heart.rotation.z=i?-.16:.18;heart.traverse(object=>{if(object.material){object.material=object.material.clone();object.material.color?.setHex(i?0x520b18:0x33070e);object.material.transparent=true;object.material.opacity=.2;object.material.depthWrite=false;}});heart.userData={base:heart.position.clone(),phase:i,priority:2,depth:'far'};background.add(heart);hearts.push(heart);animated.push(heart);});
 const leafMaterial=new THREE.MeshStandardMaterial({color:0x17261d,roughness:.88,metalness:0}),goldMaterial=new THREE.MeshStandardMaterial({color:0xc6a15b,roughness:.58,metalness:.28});[[-.7,-.66,-2.55,.42],[.74,-.38,-3.15,.36],[-1.12,.58,-4.3,.22],[1.24,.7,-4.75,.18]].forEach(([x,y,z,s],i)=>{const rose=new THREE.Group(),flower=createRose(),flourishCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-.02,-.08,-.025),new THREE.Vector3(i%2?.08:-.1,-.13,-.02),new THREE.Vector3(i%2?.18:-.2,-.09,-.015)]),gold=new THREE.Mesh(new THREE.TubeGeometry(flourishCurve,12,.006,6,false),goldMaterial);flower.scale.setScalar(s);rose.add(gold,flower);const leafCount=i===0?2:1;for(let leafIndex=0;leafIndex<leafCount;leafIndex++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.07,8,6),leafMaterial);leaf.name='BotanicalLeaf';leaf.scale.set(1.3,.32,.17);leaf.position.set((i%2?-.13:.14)+(leafIndex?-.08:0),-.1-leafIndex*.045,-.035);leaf.rotation.z=(i%2?-.62:.68)+(leafIndex?-.38:0);rose.add(leaf);}if(i<2){const card=createPlayingCard(i?'♦':'♥',i?'7':'Q');card.name='BotanicalCard';card.scale.setScalar(i?.38:.46);card.position.set(i?-.27:.25,i?.12:.03,-.09);card.rotation.set(.04,i?-.18:.18,i?-.28:.2);rose.add(card);}rose.position.set(x,y,z);rose.rotation.z=i%2?.08:-.04;rose.userData={base:rose.position.clone(),baseScale:1,priority:i>1?2:1,depth:z>-3?'near':'mid',phase:i*1.37+.4};(z>-3?foreground:midground).add(rose);roses.push(rose);animated.push(rose);});
 const petals=[];for(let i=0;i<10;i++){const petal=new THREE.Mesh(new THREE.SphereGeometry(.034+(i%3)*.004,7,5),new THREE.MeshStandardMaterial({color:i%2?0x520b18:0x751329,roughness:.82,metalness:0}));petal.name=`QueenPetal-${i}`;petal.scale.set(1,.25,.6);const angle=(i+.6)*Math.PI*2/10,radius=2.4+(i%4)*.24;petal.position.set(Math.sin(angle)*radius,.92-(i%4)*.46,-Math.cos(angle)*radius);petal.userData={base:petal.position.clone(),phase:i*1.11,priority:3,depth:i%3?'far':'mid'};background.add(petal);petals.push(petal);animated.push(petal);}
 const goldGeometry=new THREE.BufferGeometry(),goldPoints=[];for(let i=0;i<12;i++)goldPoints.push(((i*37)%101)/48-1.05,((i*61)%97)/42-.9,-4.8-(i%3));goldGeometry.setAttribute('position',new THREE.Float32BufferAttribute(goldPoints,3));const goldDust=new THREE.Points(goldGeometry,new THREE.PointsMaterial({color:0xd4b37a,size:.018,transparent:true,opacity:.28,depthWrite:false}));background.add(goldDust);
 let theme=null;function update(time,delta,{theme:nextTheme}={}){const active=nextTheme||theme||{animationSpeed:1},elapsed=visit.elapsed(time),t=elapsed*active.animationSpeed,photoMoment=motion.events&&elapsed>=3&&elapsed<=5?Math.sin((elapsed-3)/2*Math.PI):0,variant=visit.variant;cards.forEach((card,i)=>{const u=card.userData,side=Math.sign(u.base.x),flowX=Math.sin(t*u.speed+u.phase)*u.amplitudeX,flowY=Math.cos(t*(u.speed*.73)+u.phase)*u.amplitudeY,m=microMotion(t,{phase:u.phase,duration:6+i*.45,float:.012*motion.scale,rotate:.025*motion.scale,scale:u.scaleAmplitude*motion.scale});card.position.set(u.base.x+flowX+side*photoMoment*(u.depth==='near'?.11:.08),u.base.y+flowY+m.y,u.base.z+Math.sin(t*.11+u.phase)*.035);card.rotation.set(Math.sin(t*.13+u.phase)*.08,m.rotation*(i%2?-1:1),u.baseRotation+m.rotation);card.scale.setScalar(u.baseScale*m.scale);});roses.forEach((rose,i)=>{const u=rose.userData,m=microMotion(t,{phase:u.phase,duration:7+i*.6,float:.02*motion.scale,rotate:.02*motion.scale,scale:.015*motion.scale}),open=1+photoMoment*(i<2?.05:.025);rose.position.x=u.base.x;rose.position.y=u.base.y+m.y;rose.scale.setScalar(u.baseScale*m.scale*open);rose.rotation.z=m.rotation;});petals.forEach((petal,i)=>{const u=petal.userData,drift=Math.sin(t*(.18+i*.012)+u.phase);petal.position.set(u.base.x+drift*.06,u.base.y+Math.sin(t*.24+u.phase)*.1,u.base.z);petal.rotation.set((t*.08+u.phase)%(Math.PI*2),(t*.11+i)%(Math.PI*2),(t*.06)%(Math.PI*2));});hearts.forEach((heart,i)=>{const m=microMotion(t,{phase:heart.userData.phase,duration:9+i,float:.018*motion.scale,rotate:.01*motion.scale,scale:.01*motion.scale});heart.position.x=heart.userData.base.x;heart.position.y=heart.userData.base.y+m.y;heart.visible=variant!==1||i===0;});haze.material.opacity=.7+(active.name==='night'?.12:.04);goldDust.rotation.z=Math.sin(t*.08)*.025;goldDust.material.opacity=.22*(active.particleOpacity??1);}
 function responsive(width,height){const spread=width/height>1?1.25:width/height<.62?.9:1;roses.forEach(r=>{if(r.userData.originalX===undefined)r.userData.originalX=r.userData.base.x;r.userData.base.x=r.userData.originalX*spread;});applyResponsivePriority(animated,width,height);}
 return{root,update,setTheme(next){theme=next;applyThemeToRoot(root,next,'world02',{tint:.28});},responsive,reset(){visit.reset();animated.forEach(o=>o.userData.base&&o.position.copy(o.userData.base));},dispose(){disposeRoot(root);}};
}
