import test from 'node:test';
import assert from 'node:assert/strict';
import {applyTimeToFilter,CAMERA_FILTERS,cssFilter} from '../js/camera-filters.js';

test('every Wonderland world owns one centralized camera grade',()=>{assert.deepEqual(Object.keys(CAMERA_FILTERS),['world01','world02','world03','world04']);assert.equal(CAMERA_FILTERS.world02.name,'CRIMSON GARDEN');});
test('Queen grade creates a deep crimson edge while protecting the central portrait',()=>{const queen=CAMERA_FILTERS.world02;assert.ok(queen.saturation>=1.05&&queen.saturation<=1.18);assert.ok(queen.contrast>=1.03&&queen.contrast<=1.1);assert.ok(queen.sepia>=.05&&queen.sepia<=.12);assert.ok(queen.overlayOpacity>=.1&&queen.overlayOpacity<=.18);assert.ok(queen.centerOpacity>=.03&&queen.centerOpacity<=.08);assert.ok(queen.centerOpacity<queen.overlayOpacity);assert.deepEqual(queen.overlay,[120,0,20]);assert.ok(queen.brightness<=1.03);});
test('CSS filter output contains only composable mobile color operations',()=>{assert.match(cssFilter(CAMERA_FILTERS.world03),/^saturate\(.+\) contrast\(.+\) brightness\(.+\) sepia\(.+\) hue-rotate\(.+deg\)$/);});
test('Clock and Chess grades stay subtly cool while Tea stays softly warm',()=>{assert.ok(CAMERA_FILTERS.world01.hue<0);assert.ok(CAMERA_FILTERS.world03.hue<0);assert.ok(CAMERA_FILTERS.world03.sepia<.03);assert.ok(CAMERA_FILTERS.world04.brightness>1);assert.ok(CAMERA_FILTERS.world04.contrast<1);});
test('time variation stays subtle and keeps night photography bright',()=>{const base=CAMERA_FILTERS.world02,morning=applyTimeToFilter(base,'morning'),night=applyTimeToFilter(base,'night');assert.ok(morning.overlayOpacity<base.overlayOpacity);assert.ok(night.overlayOpacity>base.overlayOpacity);assert.ok(night.brightness>=base.brightness);assert.ok(night.brightness<=1.08);});
test('Queen uses the canonical world02 filter and other worlds do not inherit it',()=>{assert.equal(CAMERA_FILTERS.world02.name,'CRIMSON GARDEN');for(const id of ['world01','world03','world04'])assert.notEqual(CAMERA_FILTERS[id].name,'CRIMSON GARDEN');});
